### ISSUE TITLE
Can't install with python 3.7.4 on Windows 10

### ISSUE THREAD

**Issue by filharvey** [DidierRLopes/GamestonkTerminal#1]
tensorflow_gpu==1.1.0

is not found.

Collecting tensorflow_gpu==1.1.0 (from -r requirements.txt (line 4))
  Could not find a version that satisfies the requirement tensorflow_gpu==1.1.0 (from -r requirements.txt (line 4)) (from versions: 1.13.1, 1.13.2, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0rc0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1)
No matching distribution found for tensorflow_gpu==1.1.0 (from -r requirements.txt (line 4))

**Comment by DidierRLopes** [comment]
Hey,

Thanks for pointing out the issue.

I've used pipreqs python library to automatically create the requirements.txt file. And admittedly didn't test it myself, as I've used this before and didn't have issues.

I believe it may unintentionally have added it, sinceI never use tensorflow_gpu. I've now removed it and made sure it runs smoothly in my machine.

Let me know if ti works for you.
Thanks!

**Comment by filharvey** [comment]
Thanks got futher.

now when running the main python. These are the couple of errors I get

Traceback (most recent call last):
  File "gamestonk_terminal.py", line 12, in <module>
    from prediction_techniques import pred_menu as pm
  File "C:\GamestonkTerminal\prediction_techniques\pred_menu.py", line 13, in <module>
    from prediction_techniques import knn
  File "C:\GamestonkTerminal\prediction_techniques\knn.py", line 9, in <module>
    from TimeSeriesCrossValidation import splitTrain
ModuleNotFoundError: No module named 'TimeSeriesCrossValidation'

**Comment by DidierRLopes** [comment]
Thank you once again.

This is because that particular library was implemented by myself, and the pipreqs library didn't pick it up apparently.

I added the explanation to the install section on the readme page. You need to run this:
pip install git+https://github.com/DidierRLopes/TimeSeriesCrossValidation

Let me know if it worked :)

**Comment by DidierRLopes** [comment]
I'll close this, as I don't think this issue is no longer relevant!

**Comment by filharvey** [comment]
Sorry one more, just was able to do that last one

Traceback (most recent call last):
  File "gamestonk_terminal.py", line 12, in <module>
    from prediction_techniques import pred_menu as pm
  File "C:\GamestonkTerminal\prediction_techniques\pred_menu.py", line 16, in <module>
    from prediction_techniques import fbprophet
  File "C:\GamestonkTerminal\prediction_techniques\fbprophet.py", line 11, in <module>
    from fbprophet import Prophet
ModuleNotFoundError: No module named 'fbprophet'
