### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by BSalita** [DidierRLopes/GamestonkTerminal#110]
Windows 10 install. `pip pystan==2.18` failed when installing requirements.txt. Fix was to edit requirements.txt to change to just `pystan`.

I had edited requirements.txt with changes recommended in https://m.imgur.com/a/gqgVJPn. Perhaps that had something to do with `pystan` install breaking? Once `pystan` line was changed, all recommended changes worked great.

**Comment by DidierRLopes** [comment]
Hey @BSalita ,

Thank you for feedback. 

We're looking into making 2 requirements.txt:
- fbprophet, pystan, tensorflow, ... - only used for prediction menu
- the rest

Will close this issue now. I'll write this on my notes, thank you!
