### ISSUE TITLE
[Bug] reddit API connection issue

### ISSUE THREAD

**Issue by drzhouq** [DidierRLopes/GamestonkTerminal#113]
**Describe the bug**
when issue Reddit related commands, always get the invalid_grant error processing request

Search for latest tickers under 50 'pennystocks' posts
invalid_grant error processing request

**To Reproduce**
1. python terminal.py
2. sen
3. popular -d 5

**Screenshots**
<img width="285" alt="image" src="https://user-images.githubusercontent.com/3936288/110219333-61146f00-7e73-11eb-9738-8ddd8b899a12.png">

**Desktop (please complete the following information):**
 - OS: [. Mac BigSur]
 - Python version [e.g. 3.6.8]

**Additional context**
not quite sure about what is expected for the agent, used app name in the agent
API_REDDIT_USER_AGENT ="myStonkApp"

**Comment by DidierRLopes** [comment]
Hey @drzhouq ,

Have a look at this link for more info on each API KEY for Reddit: https://praw.readthedocs.io/en/latest/getting_started/authentication.html#script-application

Personally, my user agent is "stonks by /u/SexyYear"

Let me know if it worked!

**Comment by drzhouq** [comment]
Thanks @DidierRLopes I followed that instruction and was able to identify the issue. I have 2factor enabled on my account and that's how the authentication didn't get through. remove the 2factor and it works like a charm.
BTW, thanks for writing this app. I am still trying to figure out how to navigate it.
