### ISSUE TITLE
[IMPROVE] Should terminal --type be letters instead of numbers?

### ISSUE THREAD

**Issue by cclauss** [DidierRLopes/GamestonkTerminal#118]
**What's the feature that should be improved?**
A description of what's the feature you want improved, and a bit of context (why is that).

https://github.com/DidierRLopes/GamestonkTerminal/blob/main/terminal.py#L154
Terminal `--type` currently looks for numbers which might not be easy for users to remember correctly.

Why not use `o` for open, `h` for high, `l` for low, `c` for close, `d` for daily?  `ohc` for open, high, and close, etc.
That would be much easier for users to remember correctly.

**Describe how you would like the feature improved**
A description of what the current feature is vs what it would be after your suggestion.

**Possibly describe the ideal way to improve this**
If you have thought about how you would do it, add it here.

**Additional information**
Add any other information or screenshots about the feature improvement.

**Comment by DidierRLopes** [comment]
#127 already has this :)

**Comment by DidierRLopes** [comment]
Closing this because it has been implemented and merged.
