### ISSUE TITLE
[IMPROVE] Consider simplifying requirements.txt

### ISSUE THREAD

**Issue by gmerrall** [DidierRLopes/GamestonkTerminal#121]
The requirements.txt is a bit of a beast and I'm guessing it was generated from the output of some utility such as poetry. It probably doesn't need to be as complex as it is since it's listing every module, version and dependency. 

Can I suggest it should be modified to include only top level imports and allow individual environments to sort out dependencies? I'm not sure the app is doing anything in particular that would require pinning a specific version. 
If there is a Python dependency this could be done in code with a call to sys.version. Doing this would save you having to pin a python version to every requirement.

From a little grepping of the python files it looks like we can reduce requirements.txt to the below. This might also solve some of the funky installation issues cross-platform.  

```
alpha-vantage
beautifulsoup4
colorama
dataclasses
fbprophet
finviz
flair
fundamentalanalysis
future
holidays
iso8601
matplotlib
numpy
pandas
pandas-ta
papermill
plotly; python_version >= "3.6"
pmdarima
praw
prettytable
psaw
pystan
pytrends
quandl
rapidfuzz
requests
sklearn
tensorflow
timeseriescrossvalidation @ git+https://github.com/DidierRLopes/TimeSeriesCrossValidation.git@master
torch -f https://download.pytorch.org/whl/torch_stable.html
yfinance
```

**Comment by DidierRLopes** [comment]
I attempted this before, and I got better results with the big requirements.txt list coming from poetry. 

If you can test this, and it works, feel free to do a PR and add this requirements.txt with a name like: "requirements_top_level.txt".

**Comment by aia** [comment]
Requirements are generated by Poetry.

```
poetry export -f requirements.txt  -o requirements.txt --without-hashes
```

We use Poetry and ensure compatibility with different environments via CI - https://github.com/DidierRLopes/GamestonkTerminal/actions/runs/630217699

If you haven't used Poetry ((https://python-poetry.org/) , I highly recommend you take a look. Poetry brings sanity to dependency management in Python.

We will retire a few manually generated requirements.txt in the near feature. Manually generated requirements.txt are impossible to maintain.

**Comment by gmerrall** [comment]
I'll close this out. I thought the Poetry thing was an individual preference thing then went back and spotted the issue where it was discussed. I'll close this out.
