### ISSUE TITLE
[Bug] Deprecation notice in discovery/short_interest_api.py

### ISSUE THREAD

**Issue by gmerrall** [DidierRLopes/GamestonkTerminal#123]
Python: 3.8.8 (Mac Big Sur/Homebrew)
Pandas: 1.2.3

When going to disc -> high_short a deprecation notice is printed originating from [discovery/short_interest_api.py#L72](https://github.com/DidierRLopes/GamestonkTerminal/blob/dc2c4d905ec4253e0b4510462f4e75218ff6373f/gamestonk_terminal/discovery/short_interest_api.py#L72)

Error is
> FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.

Obviously a quick so expect a PR from me.

**Comment by aia** [comment]
https://github.com/DidierRLopes/GamestonkTerminal/pull/137
