### ISSUE TITLE
[FR] Similar tools for Crypto

### ISSUE THREAD

**Issue by IvanDePivan** [DidierRLopes/GamestonkTerminal#134]
**What's the problem of not having this feature?**
GamestonkTerminal is great at analysis of stocks, but measuring similar things in the crypto space is not yet possible.

**Describe the solution you would like**
Possibly it's hard to distinguish whether you're looking at crypto or a ticker symbol, so I suggest using a seperate flag that's not allowed to be used together with the `-t` flag:

`load -c BTC`

Then some of the optional are not compatible with crypto. e.g. use different subreddits for reddit analysis.

**Describe alternatives you've considered**
Another possible solution is a fork. This makes some sense since this is a (potentially) very large feature. However, for some subset of traders/analysts, having access to both can be useful.

**Additional information**
Obviously this is just a brainfart of mine, and not very fleshed out. I would like to test this idea here, to see if this is something that people would like.

**Comment by aia** [comment]
We maintain a project roadmap and we do have a Cryptocurrencies section - https://github.com/DidierRLopes/GamestonkTerminal/blob/main/ROADMAP.md#Cryptocurrencies.

We don't have much planned yet, but if you would like to work on certain features, please feel free to open a PR against the Roadmap document and add the features you are working on.

**Comment by DidierRLopes** [comment]
Will close this issue based on @aia's comment!
