### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by kgoswami** [DidierRLopes/GamestonkTerminal#136]
**After installation was finished (step #6) I tried "python terminal.py" and I got the error saying no module named pandas.**

"(stonkterm) C:\Users\####\Desktop\gamestonk\GamestonkTerminal>python terminal
.py
Traceback (most recent call last):
  File "terminal.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**so I installed it using "pip install pandas"**

**After this I got other errors in raw saying no module named xyz and kept doing pip install for those, following are the modules I did pip manual install for**
alpha_vantage
matplotlib
iso8601
holidays
colorama
bs4
papermill
yfinance
FundamentalAnalysis
finviz
rapidfuzz
pandas_ta
psaw
praw
prettytable
quandl
pytrends

**Comment by aia** [comment]
We have updated the installation instructions:

https://github.com/DidierRLopes/GamestonkTerminal#install

Could you check if these work for you?

**Comment by kgoswami** [comment]
I tried new steps, it worked for most part,

But I reported another ug on github yesterday,
Bug: I had to install many modules manually e.g. "pip install pandas" I
have attached whole list of modules to be installed manually.

after doing this I was able to access the terminal program.

**Comment by DidierRLopes** [comment]
Hey @kgoswami ,

I believe if you had followed the main installation guide - with poetry - you would have had more luck. Poetry takes care of the package management, and makes installation process much easier.

Will close this issue now. Feel free to re-open it if you had any other issue

**Comment by kgoswami** [comment]
Thanks for reply,

I did use poetry install, and then did manual installs.
but it is working on my end now,

Thank you,
