### ISSUE TITLE
[Bug] Calling 'help' in 'ta' and 'pred' crashes without error

### ISSUE THREAD

**Issue by Spockrates** [DidierRLopes/GamestonkTerminal#144]
**Describe the bug**
Adding the -h flag to commands in the ta and pred submenus causes GST to quit.

**Screenshots**
<img width="1025" alt="Screen Shot 2021-03-10 at 4 39 31 PM" src="https://user-images.githubusercontent.com/79881506/110701746-91377700-81bf-11eb-842f-7fba01d090ef.png">

**Desktop (please complete the following information):**
 - OS: Big Sur 11.2.3
 - Python version 3.6.8

**Comment by DidierRLopes** [comment]
Hey @Spockrates,

Good point, I'll fix this now :)

**Comment by DidierRLopes** [comment]
Closing this issue because #146 fixes this
