### ISSUE TITLE
[Bug] Typo in the fundamental analysis help menu

### ISSUE THREAD

**Issue by Spockrates** [DidierRLopes/GamestonkTerminal#149]
**Describe the bug**
It's just a typo. I'm new here and don't know the Github etiquette on reporting these, so you get a whole bug report! Kindly advise me if there is a better way.

Under Yahoo Finance API > shrs. It reads: "hareholders of the company" instead of "shareholders of the company".

**Screenshots**
<img width="472" alt="Screen Shot 2021-03-10 at 8 42 35 PM" src="https://user-images.githubusercontent.com/79881506/110723239-bccb5900-81e1-11eb-9682-2ff63744fba7.png">

**Comment by aia** [comment]
Thank you for report!

This will be fixed in https://github.com/DidierRLopes/GamestonkTerminal/pull/150/
