### ISSUE TITLE
historical data ending point. 

### ISSUE THREAD

**Issue by Quickpipsfx** [DidierRLopes/GamestonkTerminal#159]
we should also have a feature through which we can choose the chart data ending point as well so that we can predict the historical data and backtest the prediction feature and see how accurately it performs..

incase when we are not setting the ending point then it will automatically set itself to the current time as it does now

**Comment by DidierRLopes** [comment]
Hey @Quickpipsfx,

This is the same FR as #5 , I have a really clear view on how to do this and will try to get to it during weekend, but still need to fix a couple of little things before that.

Will close this based on #5 being the same

**Comment by DidierRLopes** [comment]
Only had time to work on it today during the afternoon, have a look at #169 :)
