### ISSUE TITLE
make predictive models reload existing data

### ISSUE THREAD

**Issue by sabujp** [DidierRLopes/GamestonkTerminal#16]
would be nice to have pred models like the rnn and lstm load existing data without recalculating the pred every time, assuming the input data (e.g. start date) doesn't get updated

**Comment by DidierRLopes** [comment]
Can you give further insight into this. Didn't get the idea.

**Comment by sabujp** [comment]
so if i close the graph and then type the command again, e.g. lstm or rnn, it recalculates every epoch and the final output. Why can't the output data just be saved so for the same input data set I get the same output without having to run the rnn or lstm again?

**Comment by DidierRLopes** [comment]
I get it now.

I'll add this to the future features, although with low priority. Thank you!

**Comment by DidierRLopes** [comment]
I thought about this, and was thinking if this is really necessary?

My reasoning being, 
1. This only impacts someone that wants to run the exact same model, on the exact same stock, on the exact same time frame. How many times does this happen?
2. You can save the matplotlib figure, and recall what were your conclusions. 
3. If your model is taking so long to train that this is something you see as valuable, you're likely performing overfitting.

Let me know if I'm missing something, or you disagree. Thanks!

**Comment by sabujp** [comment]
didn't check to see if we can change the epochs, if so will reduce and then see what difference it makes

**Comment by DidierRLopes** [comment]
Given our previous discussion, I'll close this ticket. Let me know if there's a clear action you'd like us to take, or feel free to open a PR against the roadmap instead
