### ISSUE TITLE
Seaborn dependency is missing [Bug]

### ISSUE THREAD

**Issue by sandsturm** [DidierRLopes/GamestonkTerminal#164]
**Describe the bug**
ModuleNotFoundError: No module named 'seaborn'

**To Reproduce**
Start from a fresh install and virtual environment. Clone the repository, install dependencies via poetry and `python terminal.py`

**Solution**
Add `seaborn = "^0.11.0"` to pyproject.toml and do a `poetry update`

**Comment by DidierRLopes** [comment]
Closing this ticket because #165 has been merged! Thanks :)
