### ISSUE TITLE
[FR] Add economic data from FRED

### ISSUE THREAD

**Issue by alexanderruchti** [DidierRLopes/GamestonkTerminal#167]
**What is FRED?**
FRED is short for the Federal Reserve Bank of St.Louis. It is one of the best free providers on economic data.

**Why would adding FRED benefit GamestonkTerminal?**
FRED offers many data series for free that give investors a decent view on how the economy (and therefore potentially the market) is going. Some noteworthy series are the _interest rate yield curve_, the _weekly initial unemployment rate_ figures, and the _break even inflation rates_.

**How to start**
FRED already offers a Python [API](https://fred.stlouisfed.org/docs/api/fred/). 

PS: I am not to lazy to do it myself, I am just a noob who only installed Git for the first time today and still don't know enough to meaningfully contribute.

**Comment by DidierRLopes** [comment]
Thanks for this, will have a look at this hopefully later this week! :)

**Comment by jmaslek** [comment]
I am willing to take a look and add something for this feature.

**Comment by DidierRLopes** [comment]
@jmaslek addressed this already in #199 ! Closing this due to that
