### ISSUE TITLE
`popular`command unexpected results

### ISSUE THREAD

**Issue by buger** [DidierRLopes/GamestonkTerminal#17]
At the moment if find stocks only in `wallstreetbets` subreddit. 

```
> popular
Search for latest tickers under 50 'pennystocks' posts
  0 tickers found.
Search for latest tickers under 50 'RobinHoodPennyStocks' posts
  0 tickers found.
Search for latest tickers under 50 'Daytrading' posts
  0 tickers found.
Search for latest tickers under 50 'StockMarket' posts
  0 tickers found.
Search for latest tickers under 50 'stocks' posts
  0 tickers found.
Search for latest tickers under 50 'investing' posts
  0 tickers found.
Search for latest tickers under 50 'wallstreetbets' posts
  23 tickers found.
```

**Comment by alexhogset** [comment]
Same!

**Comment by DidierRLopes** [comment]
Hey guys,

This is unexpected, what tickers were you using?

The only thing I can think of is that this command looks for 50 posts under a sub, from the past day, but one of the conditions that the code has is to not consider posts that have been removed by the mods. What could have happened is that it looks through 50 posts that have just been removed by the mods. Although it seems unlikely.

Can you try to use: `-l 500` which defines the limit of posts to search to 500. (I believe this is the maximum allowed by  `search_submissions`function.

Let me know how it goes

**Comment by regularperson2586** [comment]
> Hey guys,
> 
> This is unexpected, what tickers were you using?
> 
> The only thing I can think of is that this command looks for 50 posts under a sub, from the past day, but one of the conditions that the code has is to not consider posts that have been removed by the mods. What could have happened is that it looks through 50 posts that have just been removed by the mods. Although it seems unlikely.
> 
> Can you try to use: `-l 500` which defines the limit of posts to search to 500. (I believe this is the maximum allowed by `search_submissions`function.
> 
> Let me know how it goes

Dit it and same, result is 0

**Comment by DidierRLopes** [comment]
I'll have a look regarding this over the following week. Thanks for flagging this to me!

**Comment by aia** [comment]
Fixed - https://github.com/DidierRLopes/GamestonkTerminal/pull/99
