### ISSUE TITLE
[Bug] Somehow caused my Mac to kernel panic

### ISSUE THREAD

**Issue by tavurth** [DidierRLopes/GamestonkTerminal#170]
**Describe the bug**
I was loading the `pred` menu for GME, when gst caused my mac to kernel panic and restart.

**To Reproduce**
I'm not sure how to reproduce

**Screenshots**
<details>
panic(cpu 2 caller 0xffffff80134469aa): Kernel trap at 0xffffff7f974ea499, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000016, CR3: 0x00000001daf31065, CR4: 0x00000000003626e0
RAX: 0x0000000000000000, RBX: 0xffffff803dab8800, RCX: 0x0000000000000000, RDX: 0x0000000100000000
RSP: 0xffffff9145f43900, RBP: 0xffffff9145f43960, RSI: 0xffffff9145f4373a, RDI: 0xffffff803dd29000
R8:  0x000000101194cec7, R9:  0x0000000000000000, R10: 0x0000020000011000, R11: 0x00000000e355000a
R12: 0x000000000003ff40, R13: 0x0000000000000000, R14: 0xffffff91491be2f0, R15: 0xffffff914d8a2064
RFL: 0x0000000000010286, RIP: 0xffffff7f974ea499, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000000016, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0, VF: 0

Backtrace (CPU 2), Frame : Return Address
0xffffff9145f43360 : 0xffffff801331a65d 
0xffffff9145f433b0 : 0xffffff8013454a75 
0xffffff9145f433f0 : 0xffffff80134465fe 
0xffffff9145f43440 : 0xffffff80132c0a40 
0xffffff9145f43460 : 0xffffff8013319d27 
0xffffff9145f43560 : 0xffffff801331a117 
0xffffff9145f435b0 : 0xffffff8013ac1a6c 
0xffffff9145f43620 : 0xffffff80134469aa 
0xffffff9145f437a0 : 0xffffff80134466a8 
0xffffff9145f437f0 : 0xffffff80132c0a40 
0xffffff9145f43810 : 0xffffff7f974ea499 
0xffffff9145f43960 : 0xffffff7f970043fe 
0xffffff9145f439a0 : 0xffffff7f9700492f 
0xffffff9145f439d0 : 0xffffff7f9701355d 
0xffffff9145f43a10 : 0xffffff7f974f0736 
0xffffff9145f43a40 : 0xffffff7f97001eeb 
0xffffff9145f43ac0 : 0xffffff8013a5584e 
0xffffff9145f43b10 : 0xffffff8013a53ad7 
0xffffff9145f43b60 : 0xffffff8013a5cba3 
0xffffff9145f43ca0 : 0xffffff80134035e2 
0xffffff9145f43db0 : 0xffffff80133203c8 
0xffffff9145f43e10 : 0xffffff80132f6d15 
0xffffff9145f43e70 : 0xffffff801330db22 
0xffffff9145f43f00 : 0xffffff801342c065 
0xffffff9145f43fa0 : 0xffffff80132c1226 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOAcceleratorFamily2(438.7.3)[B263A05C-9992-3742-AD6C-295E68E22576]@0xffffff7f96ffb000->0xffffff7f970befff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[FF23E772-067A-3614-B922-33C82CEC0CBF]@0xffffff7f9442e000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[44472E6F-8DA0-3B46-ADEF-AFF76EC6C6DB]@0xffffff7f93d12000
            dependency: com.apple.iokit.IOSurface(269.11)[2A27F1EB-4418-37FF-82CC-9891C39C6943]@0xffffff7f958a9000
            dependency: com.apple.iokit.IOGraphicsFamily(576.1)[1279CBF9-88F1-3EB4-9566-1085DBF6DF8B]@0xffffff7f96faa000
            dependency: com.apple.iokit.IOReportFamily(47)[72B53B80-5713-30C1-BAD8-9D55FD718DA2]@0xffffff7f93c49000
         com.apple.driver.AppleIntelKBLGraphics(14.0.7)[C029CD18-859B-3594-8433-B6384B3422ED]@0xffffff7f974a0000->0xffffff7f97596fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[44472E6F-8DA0-3B46-ADEF-AFF76EC6C6DB]@0xffffff7f93d12000
            dependency: com.apple.iokit.IOSurface(269.11)[2A27F1EB-4418-37FF-82CC-9891C39C6943]@0xffffff7f958a9000
            dependency: com.apple.iokit.IOGraphicsFamily(576.1)[1279CBF9-88F1-3EB4-9566-1085DBF6DF8B]@0xffffff7f96faa000
            dependency: com.apple.iokit.IOAcceleratorFamily2(438.7.3)[B263A05C-9992-3742-AD6C-295E68E22576]@0xffffff7f96ffb000

BSD process name corresponding to current thread: Google Chrome He
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
19H2

Kernel version:
Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
Kernel UUID:
Kernel slide:     0x0000000013000000
Kernel text base: 0xffffff8013200000
__HIB  text base: 0xffffff8013100000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)
System shutdown begun: NO

System uptime in nanoseconds: 526421742715782
last loaded kext at 335292706396802: >!AXsanScheme	3 (addr 0xffffff7f97424000, size 32768)
last unloaded kext at 238175072197789: >!UAudio	323.4 (addr 0xffffff7f9765c000, size 434176)
loaded kexts:
ch.tripmode.TripModeNKE	2.0.3
>!AGraphicsDevicePolicy	5.2.6
@AGDCPluginDisplayMetrics	5.2.6
@fileutil	20.036.15
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.6f7
>!AUpstreamUserClient	3.6.8
>!APlatformEnabler	2.7.0d0
>AGPM	111.4.4
>X86PlatformShim	1.0.0
>pmtelemetry	1
>!A!IKBLGraphics	14.0.7
@Dont_Steal_Mac_OS_X	7.0.0
>!ABacklight	180.3
>BridgeAudioCommunication	6.70.7
>!AThunderboltIP	3.1.4
>!AMCCSControl	1.14
>!AAVEBridge	6.1
>!ABridgeAudio!C	6.70.7
>!AHIDALSService	1
>!AGFXHDA	100.1.429
>!A!IPCHPMC	2.0.1
>!ATopCaseHIDEventDriver	3430.1
>!A!ICFLGraphicsFramebuffer	14.0.7
>!A!ISlowAdaptiveClocking	4.0.0
@filesystems.autofs	3.0
@filesystems.apfs	1412.141.1
>BCMWLANFirmware4355.Hashstore	1
>BCMWLANFirmware4364.Hashstore	1
>BCMWLANFirmware4377.Hashstore	1
@filesystems.hfs.kext	522.100.5
@BootCache	40
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
>!AVirtIO	1.0
>!ABCMWLANBusInterfacePCIe	1
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
>!AXsanScheme	3
>usb.IOUSBHostHIDDevice	1.2
>!UAudio	323.4
>!AGraphicsControl	5.2.6
|IOAVB!F	850.1
>!ABacklightExpert	1.1.0
@!AGPUWrangler	5.2.6
>!ASMBus!C	1.0.18d1
>X86PlatformPlugin	1.0.0
|IO!BHost!CUARTTransport	7.0.6f7
|IO!BHost!CTransport	7.0.6f7
>!A!ILpssUARTv1	3.0.60
>!A!ILpssUARTCommon	3.0.60
>!AOnboardSerial	1.0
>!AActuatorDriver	3440.1
|IONDRVSupport	576.1
>!AHIDKeyboard	209
>IOPlatformPlugin!F	6.0.0d8
>!AHS!BDriver	3430.1
>IO!BHIDDriver	7.0.6f7
>!AMultitouchDriver	3440.1
>!AInputDeviceSupport	3440.8
@!AGraphicsDeviceControl	5.2.6
|IOAccelerator!F2	438.7.3
|IOGraphics!F	576.1
|IOSlowAdaptiveClocking!F	1.0.0
@plugin.IOgPTPPlugin	840.3
|IOEthernetAVB!C	1.1.0
@kext.triggers	1.0
>usb.cdc.ncm	5.0.0
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>usb.!UVHCIBCE	1.2
>usb.!UVHCI	1.2
>usb.!UVHCICommonBCE	1.0
>usb.!UVHCICommon	1.0
>!AEffaceableNOR	1.0
|IOBufferCopy!C	1.1.0
|IOBufferCopyEngine!F	1
|IONVMe!F	2.1.0
>!AThunderboltPCIDownAdapter	2.5.4
>!AThunderboltDPInAdapter	6.2.6
>!AThunderboltDPAdapter!F	6.2.6
>!AHPM	3.4.4
>!A!ILpssI2C!C	3.0.60
>!A!ILpssDmac	3.0.60
|IOSurface	269.11
@filesystems.hfs.encodings.kext	1
|IOAudio!F	300.2
@vecLib.kext	1.2.0
>!AThunderboltNHI	5.8.6
|IOThunderbolt!F	7.6.1
>!ABCMWLANCore	1.0.0
>mDNSOffloadUserClient	1.0.1b8
>IOImageLoader	1.0.0
|IOSerial!F	11
|IO80211!FV2	1200.12.2b1
>corecapture	1.0.4
|IOSkywalk!F	1
|IOUSB!F	900.4.2
>!A!ILpssI2C	3.0.60
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
>!ASMCRTC	1.0
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>!AKeyStore	2
>!UTDM	489.120.1
|IOSCSIBlockCommandsDevice	422.120.3
>!ACredentialManager	1.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|CoreAnalytics!F	1
|IOTimeSync!F	840.3
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	7.0.6f7
|IO!BPacketLogger	7.0.6f7
>!ASSE	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOUSBMass!SDriver	157.140.1
|IOSCSIArchitectureModel!F	422.120.3
|IO!S!F	2.1
|IOUSBHost!F	1.2
>usb.!UCommon	1.0
>!UHostMergeProperties	1.2
>!ABusPower!C	1.0
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1
</details>

**Desktop (please complete the following information):**
 - OS: 
<img width="213" alt="Screenshot 2021-03-14 at 20 52 08" src="https://user-images.githubusercontent.com/100964/111078559-252e7900-8507-11eb-8927-33f0ed167353.png">

 - Python version 3.6.8

**Additional context**
Nice system!

**Comment by DidierRLopes** [comment]
I've no idea what happened here! I just tested it on my macOS High Sierra and it worked well.

<img width="501" alt="Captura de ecrã 2021-03-14, às 22 52 22" src="https://user-images.githubusercontent.com/25267873/111087173-fe2c7300-8517-11eb-93a3-5be5449df7e2.png">

Have you tried again since?

**Comment by tavurth** [comment]
I've not 🤣 I'm rather nervous about things that cause my mac to restart like that.
I will try again at some point in the near future. I would say it's most likely a library that's pulled in, but I use a lot of ML libraries (mostly similar to what you have here) and I've not seen anything similar.

I will update when I have more info

**Comment by DidierRLopes** [comment]
I have Mac myself and I do get that. However, my Mac is quite old and sometimes it reboots just for the sake of it, I guess it likes to nap sometimes. :)

I'm gonna close this issue. We have over 500 forks and haven't seen this issue, so this must be something with your setup or what you were trying to do. If you try again and it re-occurs, feel free to reopen this!
