### ISSUE TITLE
Cant install poetry dependencies [Bug]

### ISSUE THREAD

**Issue by chrisg117** [DidierRLopes/GamestonkTerminal#181]
Cant seem to get the poetry dependencies to install on windows 10.

Step 5 in the installation process works fine, but I cant get through step 6.

 Every time I use 
> gst) E:\GamestonkTerminal>poetry install

I get an error saying

> Installing dependencies from lock file
> 
>   FileNotFoundError
> 
>   [WinError 2] The system cannot find the file specified
> 
>   at E:\Anaconda\envs\gst\lib\subprocess.py:1017 in _execute_child
>       1013│                                          int(not close_fds),
>       1014│                                          creationflags,
>       1015│                                          env,
>       1016│                                          os.fspath(cwd) if cwd is not None else None,
>     → 1017│                                          startupinfo)
>       1018│             finally:
>       1019│                 # Child is launched. Close the parent's copy of those pipe
>       1020│                 # handles that only the child should have open.  You need
>       1021│                 # to make sure that no handles to the write end of the

![Screen Shot 2021-03-15 at 3 48 46 PM](https://user-images.githubusercontent.com/24805108/111212582-25318600-85a6-11eb-8174-db1a3ba365e9.png)

**Comment by Pranav4399** [comment]
I'm facing this same issue. Can someone help ?

**Comment by DidierRLopes** [comment]
Hey
@chrisg117  and @Pranav4399 did you create the environment with this:

conda env create -n gst --file build/conda/conda-3-8-env.yaml

?
