### ISSUE TITLE
[Bug] crypto no longer loads (e.g. load -t btcusd -s 2017-04-01)

### ISSUE THREAD

**Issue by sabujp** [DidierRLopes/GamestonkTerminal#187]
**Describe the bug**

crypto no longer loads (e.g. load -t btcusd -s 2017-04-01)

**To Reproduce**

(✨)> load -t btcusd -s 2017-04-01

1 Failed download:
- BTCUSD: No data found, symbol may be delisted

**Desktop (please complete the following information):**
 - OS: linux
 - Python version 3.8.7

**Additional context**
this used to work, let's find the change that broke this, are we using a different default data source since 1 week ago?

**Comment by sabujp** [comment]
looks like the default source changed from alphavantage to yahoo finance (yf) so now to get btc use "load -t BTC-USD -s 2017-04-01" otherwise use --source to change the source.

**Comment by DidierRLopes** [comment]
Exactly, you need to provide `--source av`

I could have added a fallback to use AV if yahoo finance failed to be fair. But we'll be working soon on a Crypto section. So feel free to add your features request to  https://github.com/DidierRLopes/GamestonkTerminal/blob/main/ROADMAP.md
