### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Pijaycs** [DidierRLopes/GamestonkTerminal#188]
**Describe the bug**

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac Sierra]
 - Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by aia** [comment]
Unfilled template?
