### ISSUE TITLE
[Bug] fa -> fmp menu prompt shows as av

### ISSUE THREAD

**Issue by Deep-Six** [DidierRLopes/GamestonkTerminal#191]
**Describe the bug**
When Entering the fa menu followed by the fmp sub menu the prompt continues to display (fa)>(av)>

**To Reproduce**
Select fa
Then select fmp

**Screenshots**
N/A

**Desktop (please complete the following information):**
Docker container

**Additional context**
Add any other information that you think could be useful for us.

**Comment by DidierRLopes** [comment]
This is a copy-paste typo, #193 will fix this.

Thank you for pointing it out :)

**Comment by DidierRLopes** [comment]
Closing this one due to #193 being merged, thanks @Deep-Six  :)
