### ISSUE TITLE
[Bug] Papermill - Notebooks Fail to Open in Browser

### ISSUE THREAD

**Issue by ALoaf0fBread** [DidierRLopes/GamestonkTerminal#198]
**Describe the bug**
After running mill > dd -t TICKER, the Jupyter Notebook fails to open properly in browser. 

Here is an example report url: http://localhost:8888/notebooks/notebooks/reports/DHI_20210316_090911_due_diligence.ipynb

- When GST opens this in browser, I get an "Unable to Connect" error from Firefox (my default browser).
- When initiate Jupyter Notebooks from Anaconda (outside of the GST environment) I can access the notebooks just fine by navigating to the location in the URL. 
- https://imgur.com/a/UG4HI8l - here are pictures to show what happens if just running the dd -t TICKER command in Anaconda
- https://imgur.com/a/VIJiSVT - this is the output if I open an instance of Jupyter Notebook in a separate anaconda window before running the dd -t TICKER command in GST

**To Reproduce**

1. conda activate gst
2. cd c:/users/[USERNAME]/GameStonkTerminal
3. python terminal.py
4. mill
5. dd -t DHI

OR, for successful opening of notebook after running the above series of commands

1. jupyter notebook
2. *navigate to output of dd -t DHI command

**Screenshots**

- https://imgur.com/a/UG4HI8l - here are pictures to show what happens if just running the dd -t TICKER command in Anaconda
- https://imgur.com/a/VIJiSVT - this is the output if I open an instance of Jupyter Notebook in a separate anaconda window before running the dd -t TICKER command

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version 3.6.8

**Additional context**

- I'm not experienced with Jupyter Notebooks, so this could EASILY be user error on my part. This functionality just doesn't seem to work within the terminal, so I wanted to submit it. 
- I verified that Jupyter Notebooks was installed and up to date (went through install process again)
- I verified that Jupyter Notebooks functions on my computer, as I can open the .ipynb file as described above

**Comment by aia** [comment]
Are you launching

```
jupyter notebook
```

from c:/users/[USERNAME]/GameStonkTerminal?

**Comment by ALoaf0fBread** [comment]
That was the issue! When I use a separate instance of Anaconda to launch Jupyter Notebook instance from the gst environment from the c:/users/[USERNAME]/GameStonkTerminal directory, then mill > dd -t [TICKER] opens the notebook correctly in browser. 

Still requires me to open a new instance for Anaconda, but I have no clue if it's possible to streamline that. You're a wizard as far as I'm concerned, this thing is awesome.

**Comment by DidierRLopes** [comment]
> That was the issue! When I use a separate instance of Anaconda to launch Jupyter Notebook instance from the gst environment from the c:/users/[USERNAME]/GameStonkTerminal directory, then mill > dd -t [TICKER] opens the notebook correctly in browser.
> 
> Still requires me to open a new instance for Anaconda, but I have no clue if it's possible to streamline that. You're a wizard as far as I'm concerned, this thing is awesome.

I can confirm, @aia is a wizard. #welikepapermillfeature

**Comment by aia** [comment]
> Still requires me to open a new instance for Anaconda, but I have no clue if it's possible to streamline that. You're a wizard as far as I'm concerned, this thing is awesome.

For now, yes, Jupyter notebook instance needs to be launched separately. At some point we will add a job scheduler to the terminal that will give us the ability to launch background tasks including a Jupyter server. Job scheduler is a fairly large feature that will take time to get out. Simply launching and controlling Jupyter server outside of the terminal is not too much of a hassle.

**Comment by ALoaf0fBread** [comment]
Made .bat files to make this easier for myself, will share here if anyone happens to see this in the future & is as lazy as me.

**init_gst.bat** save in GamestonkTerminal folder

- set root=C:\Users\[USERNAME]\miniconda3
call %root%\Scripts\activate.bat %root%
set root=C:\Users\[USERNAME]\GamestonkTerminal
call cd C:\Users\[USERNAME]\GamestonkTerminal
call conda activate gst
python terminal.py
pause

**init_jupyter.bat** save in GamestonkTerminal folder

- set root=C:\Users\[USERNAME]\miniconda3
call %root%\Scripts\activate.bat %root% 
set root=C:\Users\[USERNAME]\GamestonkTerminal
call cd C:\Users\[USERNAME]\GamestonkTerminal
call conda activate gst
jupyter notebook
pause

**GameStonkTerminal.bat** runs both above batch files in separate instances

- set root=C:\Users\[USERNAME]\GamestonkTerminal
start %root%\init_jupyter.bat %root%
start %root%\init_gst.bat %root%

**Comment by partoneoftwo** [comment]
Installed this on a vanilla Ubuntu 2004 with Python3 virtual environment.
I can confirm, this error hit me too. The Papermill failed to spawn a Jupyter Notebook session.

The stopgap measure solution, which this thread suggested, was just to run a Jupyter Notebook session separately and manually. It lets me as a user consume the output of the Papermill. However it doesn't permanently fix this issue.

Thanks anyways.
