### ISSUE TITLE
requirements.txt errors on Ubuntu Linux

### ISSUE THREAD

**Issue by joshcoyne** [DidierRLopes/GamestonkTerminal#2]
Hey, awesome project idea! 

I tried installing this on Ubuntu Linux 20.04 but pip complains about the following:

xlwings (lets you bypass but sounds bad to do)
wheel (error)

I'm using python 3.6.13 on the aforementioned OS.

**Comment by DidierRLopes** [comment]
Hey Josh,

Thank you for raising this.

I've admittedly not tested this on Ubuntu. I'm not familiar with this error. 

Have you tried:` pip install wheel `

Is that your full error message? I'd copy paste your error message on google, because this seems to be happening before reaching the actual terminal's code.

Instead of running the requirements, you can also attempt to install each library one by one, using:
`pip install library==version`

Hope this helps,
Regards

**Comment by epigramengineer** [comment]
Running into this as well, xlwing won't be available on linux because it requires an installation of excel. Not sure if there are any work arounds.

**Comment by DidierRLopes** [comment]
Hey there!

I never import such library, my suspicion is that some other library requires it (like pandas or so), hence why pipreqs added it to the requirements list.

Can you give it a go without that package, and let me know if everything run smoothly?

Thanks for feedback!

**Comment by sigaloid** [comment]
I'm testing it right now! On KDE neon (ubuntu base).

**Comment by DidierRLopes** [comment]
Do you still get the xlwings error even though you removed that line from the requirements.txt file?

**Comment by sigaloid** [comment]
I simply ran `export INSTALL_ON_LINUX=1; pip3 install xlwings` and it installed fine.

**Comment by DidierRLopes** [comment]
Beast!! Well done. 

@joshcoyne @epigramengineer can you attempt this solution?

@sigaloid thanks for this! Do you think I should add this note somewhere on the README, for people installing from a Ubuntu machine?

**Comment by sigaloid** [comment]
Well, it installed the dependency. I get this error on run, though:
```
matt@matt:~/GamestonkTerminal$ python3 gamestonk_terminal.py map
Traceback (most recent call last):
  File "gamestonk_terminal.py", line 11, in <module>
    from sentiment import sen_menu as sm
  File "/home/matt/GamestonkTerminal/sentiment/sen_menu.py", line 5, in <module>
    from sentiment import twitter_api
  File "/home/matt/GamestonkTerminal/sentiment/twitter_api.py", line 5, in <module>
    import flair
  File "/home/matt/.local/lib/python3.8/site-packages/flair/__init__.py", line 2, in <module>
    import torch
  File "/home/matt/.local/lib/python3.8/site-packages/torch/__init__.py", line 190, in <module>
    from torch._C import *
ImportError: /home/matt/.local/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so: cannot read file data
```
Not sure if it's related to this specific dependency though.

**Comment by DidierRLopes** [comment]
I just checked and I don't import torch anywhere in the code.

There may be some convolved dependency. Can you try to upgrade your torch to: torch  1.7.1
That's the one that my machine has. So:

`pip install torch==1.7.1`

**Comment by sigaloid** [comment]
```
2021-02-24 22:29:17.109039: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-02-24 22:29:17.109083: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "gamestonk_terminal.py", line 12, in <module>
    from prediction_techniques import pred_menu as pm
  File "/home/matt/GamestonkTerminal/prediction_techniques/pred_menu.py", line 16, in <module>
    from prediction_techniques import fbprophet
  File "/home/matt/GamestonkTerminal/prediction_techniques/fbprophet.py", line 11, in <module>
    from fbprophet import Prophet
ModuleNotFoundError: No module named 'fbprophet'
```

Currently running `pip3 install fbprophet` which throws some errors about not having `lunarcalendar` as well. Trying to install lunarcalendar, then fbprophet, then running the main one. It seems the dependencies are a bit hard to track down. will report back

**Comment by sigaloid** [comment]
Here is the commands I ran (the levenshtein one may not be necessary):
```
git clone https://github.com/DidierRLopes/GamestonkTerminal
cd GamestonkTerminal/
pip3 install -r requirements.txt
export INSTALL_ON_LINUX=1; pip3 install xlwings
pip3 install -r requirements.txt
pip3 install git+https://github.com/DidierRLopes/TimeSeriesCrossValidation
pip3 install python-Levenshtein 
pip uninstall torch
pip3 uninstall torch
pip install torch
pip3 install torch
pip3 install fbprophet
python3 gamestonk_terminal.py map
```


Here is the entire command output (top one was cut off but it was just the requirements install)

**Comment by DidierRLopes** [comment]
Sweet!

Well done!! Thank you for this! It was the first screenshot I've seen of an outside user being able to use it successfully, this made my day!

PS: If you load a stock with `load -t TSLA` you'll be able to see the remaining menu options, as they required a ticker symbol!

Thanks :)

**Comment by sigaloid** [comment]
This is amazing. I've been analyzing stocks for the past 20 minutes. I hope this grows to be an even more awesome project :)

**Comment by rezart** [comment]
@sigaloid I ran the same commands as you but in the end receiving 'Illegal instruction' when I run ```python3 gamestonk_terminal.py map```. This happens with any other param that I pass to the script apart from map (like sectors, view etc). Did you run into this error at all?

**Comment by DidierRLopes** [comment]
This should be all resolved through the latest PRs with improvements in the requirements!

Will close this ticket on that basis, thanks!
