### ISSUE TITLE
Using wrong API key for AV earnings data

### ISSUE THREAD

**Issue by arcutright** [DidierRLopes/GamestonkTerminal#203]
This call should be `&apikey={cfg.API_KEY_ALPHAVANTAGE}`. It seems like their api auth sucks right now and it will happily accept `&apikey=myfakeapikey` but this should probably be fixed. [According to their docs](https://www.alphavantage.co/documentation/), this is a required parameter.

https://github.com/DidierRLopes/GamestonkTerminal/blob/bdaaca453322e1be8687040e26f2b984beeb9855/gamestonk_terminal/fundamental_analysis/alpha_vantage_api.py#L378-L381

**Comment by aia** [comment]
Thank you for the report!

Here's the fix - https://github.com/DidierRLopes/GamestonkTerminal/pull/204
