### ISSUE TITLE
[Bug]Module Not Found

### ISSUE THREAD

**Issue by groove-kidman** [DidierRLopes/GamestonkTerminal#208]
Hi,

Since I solved the WHL issues yesterday and successfully ran the script once. Now I failed ro re-run the script when I quitted and reopened the script again, with the error prompted below:

> $ python terminal.py
Traceback (most recent call last):
  File "terminal.py", line 8, in <module>
    from pandas import pandas as pd
ModuleNotFoundError: No module named 'pandas')

I have tried tusing conda install pandas again but the issue hasn't been solved. Please help me out with this issue.
Thanks.

**Comment by aia** [comment]
Did you activate your conda environment?

Run ```conda info```

**Comment by DidierRLopes** [comment]
Perfect, will close this issue then.

I think that this is because your "pip" is pointing to a python with version 2.x rather than 3.x. 

You should be able to check that with `pip --version` and `pip3 --version`. The first should tell you `(from python 2.x)` whereas the latter `(from python 3.x)`
