### ISSUE TITLE
[IMPROVE] Drop support for fbprophet

### ISSUE THREAD

**Issue by ilDon** [DidierRLopes/GamestonkTerminal#210]
**What's the feature that should be improved?**
Drop `fbprophet` from the supported prediction techniques

**Describe how you would like the feature improved**
Remove it entirely, or make it optional when installing prediction dependencies

**Possibly describe the ideal way to improve this**
Installing pystan and fbprophet on Windows is a pain in the stonks and my experience with it in predicting shares prices is usually very disappointing.

**Additional information**
First, I love this project, so please know that this issue is raised as a way to contribute, not to criticize.
Second, I have installed GameStonkTerminal just after the first post on Reddit, and it was really hard to get fbprophet to work on Windows. Now I've re-installed everything in a fresh new virtual environment and the process of getting started is so much better, really great work!
It is however still quite a pain in the stonks to get fbprophet to work on Windows 10, at least in my experience. I've solved this by entirely removing it in my installation because I find very little added value in keeping it.
I hope this helps the project and keep up the great work!

**Comment by aia** [comment]
FBprophet is indeed a mediocre component that takes significantly more resources and effort than its worth.

We can probably hide it further behind another feature flag to help people who want ML but don't want to deal with FBprophet. Truth be told, FBprophet is at the moment a proverbial egg on the ML face.

We did manage to figure out an aia-proofed way of installing FBprophet on Windows. Github CI is doing it repeatedly -  https://github.com/DidierRLopes/GamestonkTerminal/actions/workflows/windows.yml

**Comment by DidierRLopes** [comment]
Hey @ilDon,

Thanks for the feedback, and sorry for taking so long to work on this.

#335 adds a feature flag around fbprophet, so that you use it in case you set that flag to true. That should take care of this.
