### ISSUE TITLE
[IMPROVE] Question Amount

### ISSUE THREAD

**Issue by cknig** [DidierRLopes/GamestonkTerminal#217]
In Kahn, it has a certain amount of problems for what lesson you're doing it need to be less amount to have more interaction and more motivation
[math-g8-m6-topic-a-lesson-1-teacher.pdf](https://github.com/DidierRLopes/GamestonkTerminal/files/6160617/math-g8-m6-topic-a-lesson-1-teacher.pdf)
 to move to the next amount of questions.

**Comment by aia** [comment]
Doesn't look relevant to GST
