### ISSUE TITLE
[Bug] Unable to get the terminal to run based on the instructions given.

### ISSUE THREAD

**Issue by jeremyperkin** [DidierRLopes/GamestonkTerminal#222]
**Describe the bug**
Getting error when launching stating issue with alpha_vantage

file terminal.py, line 9 in module from alpha_vantage.timeseries import TimeSeries ModuleNotFoundError: no module named 'alpha_vantage'

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

Used your instructions guide.   Gave me this error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version 3.6.8

**Additional context**
Add any other information that you think could be useful for us.

Please provide an updated install instructions?

**Comment by aia** [comment]
Please take a look at the steps in Windows CI:
- https://github.com/DidierRLopes/GamestonkTerminal/actions/workflows/windows.yml
- https://github.com/DidierRLopes/GamestonkTerminal/blob/main/.github/workflows/windows.yml

**Comment by DidierRLopes** [comment]
Closing this issue based on comment provided.
