### ISSUE TITLE
[Bug] Not working on Ubuntu WSL2 for Windows

### ISSUE THREAD

**Issue by ricardofullton** [DidierRLopes/GamestonkTerminal#225]
My primary  working enviroment is Ubuntu in WSL2 on windows, all my envs and libraries are there, I followed the instructions but can't seem to get it working, I can open the terminal and run commands but there is no output with any command Can't get the terminal working properly on WSL2 ubuntu on windows 

Maybe it is not intended to work at all? will probably try straight to windows installation

**To Reproduce**
Follow install instructions on WSL2 for windows

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10 on  WSL2 for Windows 10 64b
 - Python version 3.6.8

![stonks_terminal](https://user-images.githubusercontent.com/7636119/111648538-c36e5780-8803-11eb-90a2-e98bc120d3f8.PNG)

**Comment by aia** [comment]
See https://github.com/DidierRLopes/GamestonkTerminal/issues/221

**Comment by ricardofullton** [comment]
makes sense, trying out windows directly, but man that fb-prophet lol, btw, outstanding work, congrats
