### ISSUE TITLE
[Bug] Missing fredapi from requirements files

### ISSUE THREAD

**Issue by gvikei** [DidierRLopes/GamestonkTerminal#234]
**Describe the bug**
`fredapi` is missing from `requirements-full.txt`, `requirements-old.txt` and `requirements-win.txt`

**To Reproduce**
1. Create a new conda environment, activate the environment. 
2. Install fbprophet with conda
  `conda install -c conda-forge fbprophet=0.6`
  `conda install spyder`
  `conda install gensim=3.8.3`
3. `pip install --user --requirement requirements-full.txt`
4. `python terminal.py` from GamestonkTerminal folder

**Screenshots**
![image](https://user-images.githubusercontent.com/4736266/111744978-42d24a00-8849-11eb-9c15-6465bbc29b5b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.6.8

**Comment by jmaslek** [comment]
So it should be in the poetry.lock  (install using the poetry install).  Otherwise it can just be installed with conda install/ pip install

@DidierRLopes should I still be updating the requirements.txt as well?

**Comment by DidierRLopes** [comment]
Yea, I think it doesn't hurt :) 

I'm guilty myself since I also forgot to add to the requirements.txt previously.

**Comment by jmaslek** [comment]
close via #241  ?

**Comment by pchaganti** [comment]
https://github.com/DidierRLopes/GamestonkTerminal/pull/243 @DidierRLopes @jmaslek

**Comment by DidierRLopes** [comment]
Yes, closing this now :) cheers guys
