### ISSUE TITLE
Getting Started Section

### ISSUE THREAD

**Issue by johnmathews** [DidierRLopes/GamestonkTerminal#24]
This looks super interesting and I'd like to use it, but I'm not sure how to get started.
I've installed the requirements ok, but how do I begin using it? 
It would be really useful to have a "getting started" section in the readme.

**Comment by dvergeylen** [comment]
Some insights (not a getting started guide but some guidance for non techies to use this):
https://news.ycombinator.com/item?id=26260895
https://github.com/DidierRLopes/GamestonkTerminal/issues/2#issuecomment-785552454

**Comment by johnmathews** [comment]
Great thanks. `python ganestonk_terminal.py` was what i was looking for.

**Comment by dvergeylen** [comment]
Actually `python gamestonk_terminal.py` implies your terminal's current working directory is the same as `gamestonk_terminal.py` file location. But you can start it from wherever you want either giving it a relative path from where you currently are or an absolute path ([more info](https://www.linuxnix.com/abslute-path-vs-relative-path-in-linuxunix/)).

Have fun!

**Comment by DidierRLopes** [comment]
Hey,

Yes, this is a good call. And I should have done it earlier one. Believe me that if I knew that so many people would be interested in the project, I would of!

I'm cleaning whole installation process, and then I'll write up a Getting Started document. With docker image I think this may make life much easier to non-devs.

**Comment by DidierRLopes** [comment]
Hey, let me know if this does the job:

https://github.com/DidierRLopes/GamestonkTerminal#getting-started

Will close this issue. Re-open it if you have any suggestions to improve this.
