### ISSUE TITLE
[IMPROVE] Loading Non US Stock Tickers

### ISSUE THREAD

**Issue by karan2105** [DidierRLopes/GamestonkTerminal#256]
**What's the feature that should be improved?**
I believe that changing the default source or adding a feature that allows for loading for non us tickers would massively help in the outreach of the terminal.

**Describe how you would like the feature improved**
When I try to load Indian stock tickers like SBIN , BAJAJFINSV , EICHERMOT it is unable to load the required data.

**Possibly describe the ideal way to improve this**
I believe that adding an API extension that allows for Indian market data would solve the issue. I tried searching for one and found this https://nsetools.readthedocs.io/en/latest/introduction.html . Maybe, this would be of any help...I hope.

If you guys find a solution test it out with the following tickers SBIN , BAJAJFINSV , EICHERMOT , HDFCBANK . These are all tickers of companies listed in NSE.

**Comment by DidierRLopes** [comment]
This has been raised before, I thought Yahoo Finance was doing an ok job at it. I'll try to have a look at this, I agree with you, it doesn't make sense to be limited to US stocks. Thanks!

**Comment by buzzCraft** [comment]
In my experience you need to add a .NS at the end of your ticker to load from NSE, so SBIN.NS should work

**Comment by DidierRLopes** [comment]
#327 should take care of the broken `view` in case of Indian stocks.

Also, I added a note that for Indian stocks one must use `.NS` at the end. Thanks for the tip @buzzCraft 

Closing this ticket
