### ISSUE TITLE
[Bug] - Twitter sentiment spits out 'text' when no API keys exist

### ISSUE THREAD

**Issue by Felixkruemel** [DidierRLopes/GamestonkTerminal#261]
**Describe the bug**
If you have no API keys inserted the result will be 'text'

**To Reproduce**
Just do a clean install without changing anything, load a stock, go into the ba menu and do sentiment analysis

**Screenshots**
 
![image](https://user-images.githubusercontent.com/12109804/112042567-f2f4cb00-8b47-11eb-8810-1b536c76bf90.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.6.8

**Additional context**
Additionally, when setting a day limit of e.g. 3 days it will do 4 days as the array starts at 0.

**Comment by DidierRLopes** [comment]
Thanks for this! I'll have a look at it.

PS: Regarding the additional days when looking in the past, this was a design choice. And the reason why is that if you select 3 days in the past, you gather data from 3 days in the past + the current day so far :)

**Comment by jmaslek** [comment]
Closing on #262 262
