### ISSUE TITLE
How to update?[IMPROVE]

### ISSUE THREAD

**Issue by sabirjana** [DidierRLopes/GamestonkTerminal#265]
**What's the feature that should be improved?**
I see there are frequent updates from you & team, what's the right way to update? As doing everything all over everything time is quite time-consuming. Thanks

**Describe how you would like the feature improved**
A description of what the current feature is vs what it would be after your suggestion.

**Possibly describe the ideal way to improve this**
If you have thought about how you would do it, add it here.

**Additional information**
Add any other information or screenshots about the feature improvement.

**Comment by hinxx** [comment]
I just did `git pull` inside the cloned folder. Then `git checkout <branch>` of choice if required.
That's it.
You might need to save the `gamestonk_terminal/config_terminal.py` or similar files with your local modifications before `git pull` succeeds.

**Comment by sabirjana** [comment]
Thank you!

**Comment by jmaslek** [comment]
Also make sure to install any new updates either from poetry or the requirements.txt

**Comment by sigaloid** [comment]
Perhaps add this to readme as well?

**Comment by DidierRLopes** [comment]
#327 should take care of this. Closing this ticket
