### ISSUE TITLE
Change package management to Poetry

### ISSUE THREAD

**Issue by shadycuz** [DidierRLopes/GamestonkTerminal#27]
Love the project. I think the project would see lots of benefit from moving to a different package manager then just `pip` and the `requirements.txt`. `poetry` would make it easier to support multiple Pythons like `3.6` to `3.10`. It also would help increase development velocity by making it easier to use latest versions of dependencies and making it easier to develop/contribute by having `poetry` manage the virtual environment for us. `poetry` can also help push a package to pypi if that's a direction you want to go in and I recommend you do. 

If this is something you want to explore I can push a PR with a `CONTRIBUTING.md` and `poetry` setup to manage dependencies. After that we can talk about automated testing, releases and making GameStonkTerminal `pip` installable.

Most of what I have in mind comes from [HyperModern Python](https://cjolowicz.github.io/posts/hypermodern-python-01-setup/).

**Comment by akx** [comment]
Many of the dependencies in `requirements.txt` aren't even used at the moment. I pared them down into a base + prediction (ML) set over in #26.

I used `pip-tools` to compile the unpinned versions to pinned .txt files, which isn't quite as intrusive as switching to Poetry altogether.

**Comment by shadycuz** [comment]
Well if people are interested I will do the work, but I think I'm going to let your PR get merged first. 

I'm also quite handy with CI/CD.

**Comment by binary-signal** [comment]
I can do the poetry stuff !

**Comment by DidierRLopes** [comment]
Hey guys,

I'm working on these during weekend:
- Using poetry to manage packages
- Reduce requirements to whatever is strictly necessary
- Making sure I can run a docker image from this

I'm having mostly troubles around fbprophet. But I think I should have something by tomorrow the latest.

@shadycuz I'll definitely take you on that one regarding CI/CD, we need it. Feel free to send me a PM on Linkedin or e-mail if you want to talk about it. Thanks!

@binary-signal I'm working on it at the moment. I've had a chat with a friend of mine with experience in this, and will attempt to have it done soon. But thank you. If I need some help, I may ping you a PM.

**Comment by shadycuz** [comment]
@DidierRLopes PM sent on linkedin. I think once you have poetry and the requirements undercontrol we can decide whats next. I think we could add linting and formating. It would be a PR with lots of tiny changes but no logic changes. Then probably focus on testing.

**Comment by shadycuz** [comment]
Implemented by #69
