### ISSUE TITLE
[FR] Add completion and other input usability features

### ISSUE THREAD

**Issue by brunottonurb** [DidierRLopes/GamestonkTerminal#271]
**What's the problem of not having this feature?**
I would consider myself handy with the shell, and find myself pressing tab and the arrow-keys when typing commands, and pressing the up-arrow to repeat a command with a small change. All of this does not lead to the expected behavior in GST.

**Describe the solution you would like**
It would be really cool if GST could support completion and using the arrow-keys when typing. Does the current architecture of GST allow for such a feature in theory?

**Additional information**
The haxor-news cli is also written in python and has a marvelous way of handling input. I mean the mode that is entered with the `haxor-news` command: the interactive mode. The picture illustrates the behavior.

![image](https://user-images.githubusercontent.com/6569792/112340915-4b030d00-8cc1-11eb-8bb5-0fda9c0d7708.png)

I love this application! Please keep it up <3

**Comment by brunottonurb** [comment]
I incorrectly selected the `new feature` label, but cannot change it to `enhancement`.

**Comment by DidierRLopes** [comment]
We already have this in place, you need to set the Feature Flag to True on the feature_flags.py file.

<img width="409" alt="Captura de ecrã 2021-03-24, às 21 54 40" src="https://user-images.githubusercontent.com/25267873/112388798-9cc08d00-8ceb-11eb-9e3f-2376309f894d.png">

**Comment by DidierRLopes** [comment]
Let me know if that is what you mean :)

**Comment by DidierRLopes** [comment]
Closing this because I believe this feature already exists. Feel free to reopen this ticket if you disagree

**Comment by brunottonurb** [comment]
Thanks @DidierRLopes this is what I meant.
