### ISSUE TITLE
[FR] Add in options chain to option menu

### ISSUE THREAD

**Issue by jmaslek** [DidierRLopes/GamestonkTerminal#272]
Based on discussion in #269, it would be dope to have an option to look at the option chains after you selected your expiry.

**Comment by jmaslek** [comment]
@lolrenx

**Comment by lolrenx** [comment]
Will be in the next options PR :)

**Comment by pchaganti** [comment]
This looks like it has been merged. Close this issue?

**Comment by jmaslek** [comment]
Closed on #351
