### ISSUE TITLE
[BUG] Some commands issue a line of text 

### ISSUE THREAD

**Issue by saintsupremacy** [DidierRLopes/GamestonkTerminal#275]
Reddit stock popular command seems to be finding zero stocks for everything but finding wsb posts is no problem. As mentioned though I get this line of text when I go into DD then type either "warnings" or "sec" "argument -h/--help: conflicting option strings: -h, --help" .Thats all the mishaps ive found for now. Maybe its on my end but just something that hasnt happen in previous versions. 

I no longer have trouble with poetry lock though. You can ignore that part in the title.

**Comment by DidierRLopes** [comment]
Thanks for this, regarding the last point the PR #277 should fix both of these. It was a silly mistake.

Let me have a further look to the popular command

**Comment by DidierRLopes** [comment]
Should work now. Let me know @saintsupremacy  :)

**Comment by saintsupremacy** [comment]
> Should work now. Let me know @saintsupremacy 
sorry for the late reply :p, it works! thank you.
