### ISSUE TITLE
feature request: pyinstaller binaries for terminal

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [DidierRLopes/GamestonkTerminal#28]
hi,
i think it would nice to provide binaries for "end-users" , instead of using current installation method.

``` pip install -r requirements.txt``` 

The python binaries can be built using [pyinstaller](https://www.pyinstaller.org/). However the overhead would be to build windows binary on windows computer.

regards

**Comment by akx** [comment]
Considering all the dependencies, I'm afraid this would result in an installer multiple gigabytes in size...

**Comment by DidierRLopes** [comment]
Hey @umairsiddiqui-digitek ,

This is a good idea. The issue is what @akx pointed out. There are so many libraries that the binary would be huge, and so would the time to load it. I believe the docker image will improve things massively, for non devs.

I'll close the ticket on that basis :)
