### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'statsmodels'

### ISSUE THREAD

**Issue by Grothnar1337** [DidierRLopes/GamestonkTerminal#295]
**Describe the bug**

When I run 'python terminal.py' from the Gamestonk Directory I get this error: 

raceback (most recent call last):
  File "terminal.py", line 27, in <module>
    from gamestonk_terminal.exploratory_data_analysis import eda_controller
  File "/home/user/GamestonkTerminal/gamestonk_terminal/exploratory_data_analysis/eda_controller.py", line 9, in <module>
    from gamestonk_terminal.exploratory_data_analysis import eda_api
  File "/home/user/GamestonkTerminal/gamestonk_terminal/exploratory_data_analysis/eda_api.py", line 13, in <module>
    import statsmodels.api as sm
ModuleNotFoundError: No module named 'statsmodels'

**To Reproduce**

cd GamestonkTerminal/
conda activate gst
python terminal.py 

**Screenshots**

<img width="1440" alt="Screen Shot 2021-03-29 at 8 34 31 PM" src="https://user-images.githubusercontent.com/81600742/112921685-d79e3880-90d0-11eb-86e2-9c7ad1ad551e.png">

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux, 10 (buster) 
 - Python version: Python 3.8.5

**Additional context**

Trying to run on a VM in Google cloud.....hopefully I am just missing something dumb but I have tried all the suggestions in the Getting started.

**Comment by jmaslek** [comment]
If you do pip install statsmodels does that fix?

Looks like recent PR didn't update requirements.txt.  (Did you install from requirements.txt or poetry)?

**Comment by Grothnar1337** [comment]
> pip install statsmodels

that fixed the problem, I had to run that command for a few more dependencies as well that popped up. 

I installed from poetry

**Comment by zakiaziz** [comment]
I just installed today and still having this issue. I'm able to fix it via `pip install <package_name>` but seems like this issue should still be open.

**Comment by DidierRLopes** [comment]
@zakiaziz  thanks for feedback. I think #358 should fix this now
