### ISSUE TITLE
[Bug] ModuleNotFound error upon installation

### ISSUE THREAD

**Issue by megadan21** [DidierRLopes/GamestonkTerminal#296]
**Describe the bug**

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac Sierra]
 - Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by megadan21** [comment]
I followed all of the commands that was presented in the readme, but when I try to run the terminal, I get the error message: " ModuleNotFoundError: No module named 'statsmodels' ". I am on windows 10 using python version 4.9.2

**Comment by jmaslek** [comment]
Try pip install statsmodels

Looks like it needs to be added to requirements.txt

**Comment by megadan21** [comment]
Worked! Thank you
