### ISSUE TITLE
Yahoo daily API is going to be a history

### ISSUE THREAD

**Issue by WyattLiu** [DidierRLopes/GamestonkTerminal#321]
Hi There,

I just found out this on the website:
https://developer.yahoo.com/api/
"On approximately May 1, 2021, the free Yahoo Weather API will be retired and will cease to function. Unfortunately, we will not be offering a replacement API, and there will be no paid alternative."

May I ask what would be the second-best API we should buy and could we have more detailed instructions on what to do?

**Comment by jmaslek** [comment]
That's just the weather one.

Yahoo finance (yfinance) is a third party api

**Comment by WyattLiu** [comment]
Oh, I was stupid. Thank you!
