### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by gergi** [DidierRLopes/GamestonkTerminal#325]
**Describe the bug**
Install instructions do not cover required modules.

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior
1. Install Anaconda
1. Verify `conda -V` : _conda 4.9.2_
1. `conda create -n gst python=3.6.8`
1. `conda activate gst`
1. `git clone https://github.com/DidierRLopes/GamestonkTerminal.git`
1. `cd GamestonkTerminal/`
1. `conda install poetry`
1. `poetry install`
1. `python terminal.py`

Fails with "ModuleNotFoundError: No module named 'statsmodels'"

Running `conda install statsmodels` resolves that specific issue. However, `python terminal.py` then fails with "ModuleNotFoundError: No module named 'pmdarima'". `conda install pmdarima` does not resolve this issue as it says no package found with that name.

**Screenshots**
![Screenshot from 2021-04-09 15-06-05](https://user-images.githubusercontent.com/573211/114245739-e1803100-9945-11eb-8998-89d53f47bc37.png)

**Desktop (please complete the following information):**
 - OS: Pop! Linux 5.8.0
 - Python version: 3.6.8

**Additional context**
Add any other information that you think could be useful for us.

**Comment by jmaslek** [comment]
Look at #302.

pmdarima has to be installed through pip.

**Comment by DidierRLopes** [comment]
#327 makes this more specific on the README. Hence, closing this ticket
