### ISSUE TITLE
[BUG] macOS Installation without Conda

### ISSUE THREAD

**Issue by Amar1729** [DidierRLopes/GamestonkTerminal#328]
Not exactly a bug, but working steps to build this on macOS without Conda. Sorry if this is in the wrong place - just thought it could be useful for others. This may be out of scope, but would you accept a PR for another mac github workflow that tested this project without using conda?

#### Without ML
There are a few homebrew packages required to install several of the python modules, since not all of this project's dependencies ship with pre-built wheel files for macOS.

```
brew install freetype gcc
brew install hdf5@1.8  # NOT the current hdf5 (1.12) but the versioned 1.8. gamestonk currently uses h5py==2.10.0 which doesn't like hdf5 1.12.
brew install sentencepiece
brew install python-tk  # tkinter support for homebrew's python3
```

Note - there may be a few others required that I'm not sure of, but these are the more uncommon ones that you may not have installed already.

Once you have poetry installed, you can run `poetry install` and `poetry run pytest tests/` to verify the install is working.

#### With ML

Install required modules with `poetry install -E prediction`. One of the required modules, `tokenizers`, requires a working Rust compiler to build (`brew install rust rustup-init`). However, I was running into problems with building the module, not sure why yet.

----

**Describe the bug**
- related: #42 
- post-Catalina, it may be necessary to link some of xcode's development headers into `/usr/local/include` yourself (don't do this unless you run into problems with using gcc) https://github.com/DidierRLopes/GamestonkTerminal/issues/186#issuecomment-800798056

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 Mojave
 - Python: latest Homebrew `python3.9.2`

**Additional context**
Add any other information that you think could be useful for us.

**Comment by aia** [comment]
Dependencies and multiple ways of managing them is by far the most problematic part of the Python experience for users.

We made a very deliberate choice of committing only to Anaconda support on Windows and Mac. Anaconda allows to install and configure advanced python packages without having a C compiler or libraries installed. Anaconda is the most widely used Python distribution in data science and machine learning communities.

Supporting different platforms and distribution is a very expensive proposition for an open source project. Support for Windows installation was a controversial decision for us (some believed that it would be prohibitively expensive). Our commitment to support a platform/distribution/path is perpetual - meaning we will have to maintain compatibility for all future changes that we make to the project.

As a project, our goal is to build "a modern Python-based integrated environment for investment research, that allows the average Joe-retail-trader to leverage state-of-the-art Data Science and Machine Learning technologies." Any resources that we spend supporting multiple ways to install the project are the resources we take away from building the core of our product.

I do not see a compelling reason to support any installation path outside of Anaconda.

**Comment by Amar1729** [comment]
Yeah, that's a fair reasoning, thanks for the explanation. Thought I'd post the things I needed here in the small chance they were useful to others but no worries if not. Thanks for the work on this project!
