### ISSUE TITLE
Create github issue templates

### ISSUE THREAD

**Issue by sigaloid** [DidierRLopes/GamestonkTerminal#33]
I'd make a PR for this, but I'm not sure exactly how the file structure works and else I'd need manage repo. This would help manage the issues coming in.

https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by DidierRLopes** [comment]
Hey @sigaloid ,

This is a really good idea. Feel free to make a PR for this. What would you need from me in order to do so?

**Comment by sigaloid** [comment]
I would need `manage repo` access to add them. Don't worry about it, I'm working on a PR
