### ISSUE TITLE
[Bug] Mentions don't show properly after viewing RTP Sectors

### ISSUE THREAD

**Issue by blacktide082** [DidierRLopes/GamestonkTerminal#330]
**Describe the bug**

When trying to view the `ba` > `mentions` command, it does not show properly if the last command viewed was `disc` > `rtp_sectors`.

**To Reproduce**

- Load any ticker: `load -t GME`
- Enter command `disc`
- Enter command `rtp_sectors`
- Quit disc - `q`
- Enter command `ba`
- Enter command `mentions`

**Screenshots**

This is the chart that is displayed after following these steps:

![Screen Shot 2021-04-11 at 8 32 13 PM](https://user-images.githubusercontent.com/61211787/114327020-5d74a780-9b05-11eb-8280-202b29a71ee7.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.1
 - Python version 3.6.8

**Comment by DidierRLopes** [comment]
Thank you for reporting this. #334 should fix this
