### ISSUE TITLE
[Bug] ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by arisliang** [DidierRLopes/GamestonkTerminal#340]
**Describe the bug**
Installation error when running `poetry install`

**To Reproduce**
Follow official installation steps in README. The error occurred when running `poetry install`

**Screenshots**
![image](https://user-images.githubusercontent.com/1115503/114547040-7f4e6580-9c90-11eb-84c7-540a65530579.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version 3.7.10

**Comment by aia** [comment]
On Windows follow these steps:

https://github.com/DidierRLopes/GamestonkTerminal/runs/2335554055

**Comment by aia** [comment]
assuming this is resolved.
