### ISSUE TITLE
[FR] Add failure to deliver information

### ISSUE THREAD

**Issue by hinxx** [DidierRLopes/GamestonkTerminal#362]
**What's the problem of not having this feature?**

I have not found information about the stock's failure to deliver (FDT) reports from https://www.sec.gov/data/foiadocsfailsdatahtm. Is it already in the tool?

**Describe the solution you would like**

Add a command to show the current FDT status of a loaded ticker (in dd menu?).
Maybe show some history as well (i.e. last 5 months == 10 rows of data).

**Additional information**

The data is updated twice per month. Data is packaged in zip files :face_with_head_bandage:. Archive contains as single text/CSV file for all the tickers. Data is reported with two week delay.

See also https://github.com/NibbieHub/FailureToDelivers. This project is serving a different and narrow purpose, but can be a seen as a reference nevertheless.

If of interest I can try to make a PR for this.

**Comment by DidierRLopes** [comment]
![25a](https://user-images.githubusercontent.com/25267873/115126470-1be17200-9fc7-11eb-83a4-badc06dfe392.jpg)

Let's do it! Sounds great!!

**Comment by hinxx** [comment]
Never enough memes :rofl:
