### ISSUE TITLE
[IMPROVE] Adding Degiro as a broker

### ISSUE THREAD

**Issue by Deel18** [DidierRLopes/GamestonkTerminal#364]
Hi! 

Kinda new to open source so please let me know if I need to submit this differently. 

I've been working on adding support for Degiro as a broker for myself through the terminal, so far I've implemented regular login and also 2FA and also a command to see your current portfolio and current cash holding. Nothing fancy so far, but figured I would ask if there is some interest for me to develop this further and maybe add it for other Degiro users?

I used the [Unofficial Api](https://github.com/lolokraus/DegiroAPI) but with some changes implemented by a different user that submitted a [PR](https://github.com/lolokraus/DegiroAPI/pull/12) which was never added due to the original author being unresponsive.

If there is any interest I can try to make a PR for this.

Also looking into adding Avanza (Swedish broker) as another alternative too...

**Comment by jmaslek** [comment]
Feel free to make it a PR!  

Definitely open to as many brokers as people are willing to contribute!

**Comment by DidierRLopes** [comment]
Yess @Deel18 !

We are always keen on new contributions!

Also, I think across the maintainers none of us has a degiro account, so it would be great if you could work on this feature! A lot of people would appreciate such!

Same goes for adding Avanza :)

**Comment by Deel18** [comment]
Awesome! I'll get right on it then! :)

**Comment by DidierRLopes** [comment]
> Awesome! I'll get right on it then! :)

Super, we have a discord chat now. Feel free to pop in there if you have any questions or want to discuss implementation :)

**Comment by hinxx** [comment]
I'm using degiro and looking into using avanza for my todler hodler's investments :gem:. Looking forward to the PR! :+1:

**Comment by Deel18** [comment]
@DidierRLopes
Seems like the Discord link is invalid or I need an invite. Could you please renew it or send me an invite? :)

**Comment by jmaslek** [comment]
https://discord.gg/cC2KNt4B

**Comment by DidierRLopes** [comment]
Closing this due to #381 ! Nice job @Deel18
