### ISSUE TITLE
[FR]Implied Volatility rank and percentile

### ISSUE THREAD

**Issue by pchaganti** [DidierRLopes/GamestonkTerminal#368]
**What's the problem of not having this feature?**
One of the things that is really nice in the better options apps is the ability to get IV rank and percentile info for tickers. This is quite useful to see how current IV for options compares to historical volatility.

**Describe the solution you would like**
Maybe an additional menu option to display this info for a loaded ticker if we are in the options view?

**Describe alternatives you've considered**

**Additional information**
This info is not available from RH or Yahoo Finance. I am not sure about Tradier or other sources. 
One example of this info (SPY) - https://www.alphaquery.com/stock/SPY/volatility-option-statistics/30-day/iv-mean

thanks!

**Comment by jmaslek** [comment]
How does #375 address this?

**Comment by pchaganti** [comment]
Works great! Looks awesome!

thanks!

<img width="416" alt="ivrank" src="https://user-images.githubusercontent.com/6500/115484243-76293f80-a220-11eb-83dc-22995b197223.png">

**Comment by jmaslek** [comment]
No problem!  Thanks for the suggestion!

As an aside was the selenium part straightforward?

**Comment by pchaganti** [comment]
Quite simple.

- pip install selenium
- download chrome driver from google https://sites.google.com/a/chromium.org/chromedriver/downloads
- put it in the PATH and update config_terminal.py
