### ISSUE TITLE
[IMPROVE] Add more Crypto Currency assets

### ISSUE THREAD

**Issue by partoneoftwo** [DidierRLopes/GamestonkTerminal#374]
**What's the feature that should be improved?**
As a trader with diamond hands I would like to use GamestonkTerminal to analyze my porfolio of invested crypto assets.
I tried to look for my the crypto assets I have invested in, using this application and it could not resolve the crypto asset codes.

**Describe how you would like the feature improved**
In the altcoin world many new assets pop up weekly, however I think it is not unheard of to think that this application could handle the Coinmarketcap.com top 100 coins.

If that goal is too lofty, then perhaps at least the top 20.

**Possibly describe the ideal way to improve this**
Make use of API access to the largest Crypto exchanges and fetch the data here.

**Additional information**
No further additional information.

**Comment by jmaslek** [comment]
> I tried to look for my the crypto assets I have invested in, using this application and it could not resolve the crypto asset codes.

Are you using RH for crypto?  I currently have it to get stocks only (no crypto or options), so I can open an issue for that specifically.  

As for other API's like you referenced, I don't see why we couldn't look into some of those (or if you are familiar at all?)

**Comment by jmaslek** [comment]
How does #378 address this?

**Comment by peter-clemenko** [comment]
CCXT might help with this

**Comment by jmaslek** [comment]
Im gonna close this on #378 , #428
