### ISSUE TITLE
Error on installation  • Installing scs (2.1.3): Failed 

### ISSUE THREAD

**Issue by sidguez** [DidierRLopes/GamestonkTerminal#389]
when runing _poetry install_ i get this error : [https://pastebin.com/Hhss4GTU](https://pastebin.com/Hhss4GTU)
thanks for your help.
i'm using ubuntu 20.04 LTS.

**Comment by jmaslek** [comment]
I can't seem to open the image you linked

**Comment by aia** [comment]
Compiler on your system is having a problem:

```
error: Command "gcc -pthread -B /home/myadmin/anaconda3/envs/gst/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPYTHON -DCTRLC=1 -DDLONG=1 -DCOPYAMATRIX -DUSE_LAPACK -DSCIPY_MKL_H -DHAVE_CBLAS -DSCIPY_MKL_H -DHAVE_CBLAS -Iscs/include -Iscs/linsys -Iscs/linsys/cpu/direct/ -Iscs/linsys/external/amd -Iscs/linsys/external/dqlql -I/home/myadmin/anaconda3/envs/gst/lib/python3.6/site-packages/numpy/core/include -I/home/myadmin/anaconda3/envs/gst/include -I/home/myadmin/anaconda3/envs/gst/include -I/home/myadmin/anaconda3/envs/gst/include/python3.6m -c src/scsmodule.c -o build/temp.linux-x86_64-3.6/src/scsmodule.o -O3" failed with exit status 127
```

**Comment by aia** [comment]
Take a look at how the build does it

https://github.com/DidierRLopes/GamestonkTerminal/runs/2424128238

**Comment by DidierRLopes** [comment]
@sidguez can you see if this solves it: https://github.com/DidierRLopes/GamestonkTerminal/blob/main/TROUBLESHOOT.md

**Comment by desivanrintel** [comment]
Running setup.py install for scs ... error

**Comment by hinxx** [comment]
@sidguez seems like your anaconda wants to run on python3.6. It just happens that it fails for me, too, when using python3.6 as well, I can see the error:
```
    RuntimeError: Python version >= 3.7 required.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/12/bd/1ab6a3b3f2791741e6e7c142f932ea1808277e92167e322dec43271b2225/scs-2.1.3.tar.gz#sha256=7c9ca6730638abcbd004909e7f4816b9e2c1486d3e864b1a26261ca84002cbf0 (from https://pypi.org/simple/scs/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement scs==2.1.3 (from versions: 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.0.6, 1.0.7, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.7, 1.2.1, 1.2.2, 1.2.3, 1.2.5, 1.2.6, 1.2.7, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.1.post2, 2.1.2, 2.1.3)
ERROR: No matching distribution found for scs==2.1.3
```
`scs` seems to crave for python3.7 or newer.

**Comment by desivanrintel** [comment]
for reference: it was apparently a macos problem linked to xcode.  I followed the following solution & it worked out https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

**Comment by sidguez** [comment]
thank you all for your answers.
I have fixed it 3 days ago by running `conda install -c conda-forge fbprophet numpy=1.19.5 hdf5=1.10.5` and then continue the install by `poetry install`
