### ISSUE TITLE
[ERROR] after install "import yfinance as yf" "ModuleNotFoundError: No module named 'yfinance'"

### ISSUE THREAD

**Issue by kubus6983** [DidierRLopes/GamestonkTerminal#390]
Followed install process to a t - receive this error when attempting to launch terminal.

(gst) C:\Users\polsk>cd GameStonkTerminal/

(gst) C:\Users\polsk\GamestonkTerminal>python terminal.py
Traceback (most recent call last):
  File "terminal.py", line 9, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'

(gst) C:\Users\polsk\GamestonkTerminal>

**Comment by jmaslek** [comment]
So to fix this you run `pip install yfinance`

Poetry does all the installs so this error means you likely need to do `poetry install`

**Comment by aia** [comment]
Make sure you are running poetry install in the GamestonkTerminal directory.

Here's how it should look like:
https://github.com/DidierRLopes/GamestonkTerminal/runs/2427205538?check_suite_focus=true

**Comment by jmfc01** [comment]
If it continues to need items installed after yfinance, check that you have the latest and greatest c++ . I got hung up there and was quickly frustrated. Check this link to update. https://docs.microsoft.com/en-us/answers/questions/136595/error-microsoft-visual-c-140-or-greater-is-require.html

**Comment by DidierRLopes** [comment]
I've added some common issues to this page:
https://github.com/DidierRLopes/GamestonkTerminal/blob/main/TROUBLESHOOT.md

Will close this issue. Let us know if you still have issues that aren't mentioned in this page
