### ISSUE TITLE
[Bug] Poetry Install Issue

### ISSUE THREAD

**Issue by SW386** [DidierRLopes/GamestonkTerminal#393]
I am having an issue install fbprophet using poetry install -E prediction
This is my computer output:

  • Installing fbprophet (0.6): Failed

  EnvCommandError

  Command ['/Users/Shufan/opt/anaconda3/envs/foss_terminal/bin/pip', 'install', '--no-deps', 'file:///Users/Shufan/Library/Caches/pypoetry/artifacts/38/a1/e8/f1fb6256459d92553a2e07843275619bc77130ffb28b96c4b6edb7a34a/fbprophet-0.6.tar.gz'] errored with the following return code 1, and output: 
  Processing /Users/Shufan/Library/Caches/pypoetry/artifacts/38/a1/e8/f1fb6256459d92553a2e07843275619bc77130ffb28b96c4b6edb7a34a/fbprophet-0.6.tar.gz
  Building wheels for collected packages: fbprophet
    Building wheel for fbprophet (setup.py): started
    Building wheel for fbprophet (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Users/Shufan/opt/anaconda3/envs/foss_terminal/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/1b/4tp5p3k121j4pty85ncsxxhc0000gp/T/pip-req-build-spmxln6v/setup.py'"'"'; __file__='"'"'/private/var/folders/1b/4tp5p3k121j4pty85ncsxxhc0000gp/T/pip-req-build-spmxln6v/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/1b/4tp5p3k121j4pty85ncsxxhc0000gp/T/pip-wheel-b12zqwv6
         cwd: /private/var/folders/1b/4tp5p3k121j4pty85ncsxxhc0000gp/T/pip-req-build-spmxln6v/
    Complete output (9 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_888a84912910fa0a45b9d614b75bb8a8 NOW.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
    ERROR: Failed building wheel for fbprophet
    Running setup.py clean for fbprophet
  Failed to build fbprophet
  Installing collected packages: fbprophet
      Running setup.py install for fbprophet: started
      Running setup.py install for fbprophet: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /Users/Shufan/opt/anaconda3/envs/foss_terminal/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/1b/4tp5p3k121j4pty85ncsxxhc0000gp/T/pip-req-build-spmxln6v/setup.py'"'"'; __file__='"'"'/private/var/folders/1b/4tp5p3k121j4pty85ncsxxhc0000gp/T/pip-req-build-spmxln6v/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/1b/4tp5p3k121j4pty85ncsxxhc0000gp/T/pip-record-mehbdrv7/install-record.txt --single-version-externally-managed --compile --install-headers /Users/Shufan/opt/anaconda3/envs/foss_terminal/include/python3.6m/fbprophet
           cwd: /private/var/folders/1b/4tp5p3k121j4pty85ncsxxhc0000gp/T/pip-req-build-spmxln6v/
      Complete output (9 lines):
      running install
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/fbprophet
      creating build/lib/fbprophet/stan_model
      INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_888a84912910fa0a45b9d614b75bb8a8 NOW.
      error: command 'gcc' failed with exit status 1
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /Users/Shufan/opt/anaconda3/envs/foss_terminal/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/1b/4tp5p3k121j4pty85ncsxxhc0000gp/T/pip-req-build-spmxln6v/setup.py'"'"'; __file__='"'"'/private/var/folders/1b/4tp5p3k121j4pty85ncsxxhc0000gp/T/pip-req-build-spmxln6v/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/1b/4tp5p3k121j4pty85ncsxxhc0000gp/T/pip-record-mehbdrv7/install-record.txt --single-version-externally-managed --compile --install-headers /Users/Shufan/opt/anaconda3/envs/foss_terminal/include/python3.6m/fbprophet Check the logs for full command output.

**Comment by aia** [comment]
You want to install fbprophet with conda before running poetry like so:

https://github.com/DidierRLopes/GamestonkTerminal/runs/2427205238?check_suite_focus=true

**Comment by DidierRLopes** [comment]
Have a look at https://github.com/DidierRLopes/GamestonkTerminal/blob/main/TROUBLESHOOT.md.

Closing this issue for now. Feel free to re-open it if you couldn't solve it.
