### ISSUE TITLE
[Bug] Options max pain

### ISSUE THREAD

**Issue by spartan737** [DidierRLopes/GamestonkTerminal#402]
GME max pain for 30/04/2021 is $420, but from SwaggyStocks, its only $155. TSLA is $800 here, $720 in SwaggyStocks. NIO max pain is almost similar to SwaggyStocks ($37.5 vs $38), SPY very similar ($410 vs $415). Please check it out. Thanks

**Comment by jmaslek** [comment]
Closed #407
