### ISSUE TITLE
[Bug] Regarding Discord Links

### ISSUE THREAD

**Issue by FrankHu-RDS** [DidierRLopes/GamestonkTerminal#411]
**Describe the bug**
It looks like when you click the discord buttons in the README, it sends you here:
https://camo.githubusercontent.com/1f267821594e4cc9a753e460a3750fec544f1d4a6d6a91f2fcc5ebaaf33adf05/68747470733a2f2f646973636f72646170702e636f6d2f6170692f6775696c64732f3833313136353738323735303738393637322f7769646765742e706e673f7374796c653d736869656c64
https://camo.githubusercontent.com/9a28b7ae1acf1f35f30eadb943eca63260d5d3479b27dd59399a0b21dd300fbc/68747470733a2f2f646973636f72646170702e636f6d2f6170692f6775696c64732f3833313136353738323735303738393637322f7769646765742e706e673f7374796c653d62616e6e657232

Is this intended? 

I ask as I had to really dig to look for the discord join link button. 

**To Reproduce**
Go to Readme
Click on discord image links. 

**Screenshots**
![image](https://user-images.githubusercontent.com/51103251/116342049-d24b1100-a796-11eb-9c2e-54f6501d5488.png)
![image](https://user-images.githubusercontent.com/51103251/116342061-d4ad6b00-a796-11eb-829e-1c3136afe409.png)

**Desktop (please complete the following information):**
Unnecessary.

**Comment by Soda-City-PoGo** [comment]
i have many questions, i would like to join this discord 💯 plx fix link for simple ape.

**Comment by jmaslek** [comment]
Noted.  The link will be in a PR soon.

https://discord.gg/Up2QGbMKHY

**Comment by jmaslek** [comment]
Correct link added in #415
