### ISSUE TITLE
[Bug] Failing to install pyportfolioopt

### ISSUE THREAD

**Issue by ip151515** [DidierRLopes/GamestonkTerminal#412]
I can't get the terminal to run because it says pypfopt module is missing.
For the other modules missing I used pip install (nameofthemodule), but for pypoft I get this
![image](https://user-images.githubusercontent.com/83357670/116427620-78088980-a844-11eb-8231-1ec4340c7a8b.png)

Sorry if anyhing's not clear but I'm no expert.

**Comment by jmaslek** [comment]
So check out the troubleshooting : https://github.com/DidierRLopes/GamestonkTerminal/blob/main/TROUBLESHOOT.md

That seems consistent with folks that have had to install updated C++.

**Comment by alokan** [comment]
https://pypi.org/project/pyportfolioopt/

Under getting started it has a download link for c++ in a note. It says you need to install that first for pyportfolioopt to work on windows. Have you tried that?

**Comment by ip151515** [comment]
Thank you for your answers, I did install c++ Visual Build tools but I keep getting the same error

**Comment by alokan** [comment]
Can you get scs installed through conda or poetry?

**Comment by ip151515** [comment]
Thank you, it worked.
I went on installing modules and now I'm stuck with the coinmarketcapapi one.
I installed more than one version of the coin market cap api but I'm still getting the error.

**Comment by alokan** [comment]
pip install python-coinmarketcap
Should be the right one. It's a different name from what shows up in the error.
