### ISSUE TITLE
[Bug] fx> summary command error:  Insufficient authorization to perform request

### ISSUE THREAD

**Issue by arisliang** [DidierRLopes/GamestonkTerminal#417]
**Describe the bug**
I've added my oanda API key to GT_OANDA_TOKEN and GT_OANDA_ACCOUNT in .env file, but got error "Insufficient authorization to perform request" when running "fx" -> "summary"

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior
1. Added oanda API key to GT_OANDA_TOKEN and GT_OANDA_ACCOUNT in .env file
2. fx
3. summary

**Screenshots**
![image](https://user-images.githubusercontent.com/1115503/116726380-c3be5d00-aa15-11eb-8e9b-c6cfefee7802.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version 3.6.13

**Comment by alokan** [comment]
Are you sure the account number and keys were added correctly?

**Comment by arisliang** [comment]
Yeah, I'm sure the account number and keys are correct. Although is there something on Oanda we could give sufficient authorization to these keys? I suspect some additional Oanda configuration for these keys are needed.

**Comment by alokan** [comment]
No, there isn't anything on Oanda that you need to change. Are you using a live account?

**Comment by arisliang** [comment]
Yes, it's a live account. I just generated a new token from the account, doesn't help. I use the account and key with a previously working script, it wasn't working either. I contact Oanda support, see if they can help to check.

**Comment by DidierRLopes** [comment]
I've created a Oanda account just to test this Forex menu and didn't have any issue.

I'm gonna change some digits but this is what my OANDA details look like:
```
OANDA_ACCOUNT = "101-000-6233123-121"
OANDA_TOKEN = "55a7c1234d5a3531a613ffff713fb68f-5e72de1d26934274359ef7ddb99efe50"
```

Can you confirm you are setting these correctly?

**Comment by arisliang** [comment]
Yeah, what I put looks like these as well (only anonymized).

>GT_OANDA_ACCOUNT=001-003-1234567-001
GT_OANDA_TOKEN=1111111111111111111111111111111-222222222222222222222222222222

**Comment by alokan** [comment]
Is the key a V20 REST API key?

**Comment by arisliang** [comment]
Somehow it's working with oanda summary now. Not sure if it's because I did a git pull.

**Comment by arisliang** [comment]
By the way, I understood from Oanda support their base url for live and practice account are different. So this only works with live account, is it?

**Comment by devwolff** [comment]
I'm using an practice account. So I changed environment from "live" -> "practice". I also got "Insufficient authorization to perform request". 
 
Just double checking.. So the code on oanda only work with "live" account?

I tried below with my practice account

```
curl -H "Authorization: Bearer 12345678900987654321-abc34135acde13f13530" https://api-fxpractice.oanda.com/v3/accounts/{account_ID}/summary
```

and it works fine.
