### ISSUE TITLE
[Bug] "ba" -> "wsb" error: invalid_grant error processing request

### ISSUE THREAD

**Issue by arisliang** [DidierRLopes/GamestonkTerminal#419]
**Describe the bug**
After setting up reddit keys, unable to open "ba" -> "wsb", it gives error:
>invalid_grant error processing request

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior
1. setting up reddit keys: `GT_API_REDDIT_CLIENT_ID`, `GT_API_REDDIT_CLIENT_SECRET`, `GT_API_REDDIT_USERNAME`, `GT_API_REDDIT_USER_AGENT`
2. load any ticker, e.g. MSFT
3. ba
4. wsb
5. error: invalid_grant error processing request

**Screenshots**
![image](https://user-images.githubusercontent.com/1115503/116767347-2f2e1c00-aa62-11eb-9c9a-224043588a45.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: 3.6.13

**Additional context**
Is this the correct fields to take from Reddit?
![image](https://user-images.githubusercontent.com/1115503/116767793-0d826400-aa65-11eb-8365-7c65cf8af561.png)

**Comment by alokan** [comment]
Yes, those are correct. Did you set up GT_API_REDDIT_PASSWORD as well?

**Comment by arisliang** [comment]
What is the password for? Not just client id and secret?

**Comment by alokan** [comment]
For the api call to work properly it needs your reddit password.

**Comment by arisliang** [comment]
After filling up the reddit password, it works now. Thanks!
