### ISSUE TITLE
Unable to run dd->rating, how to specify FMP key?

### ISSUE THREAD

**Issue by arisliang** [DidierRLopes/GamestonkTerminal#421]
**Describe the bug**
Unable to run dd->rating

**To Reproduce**
1. load any ticker, e.g. MSFT
2. dd
3. rating
4. error 

**Screenshots**
![image](https://user-images.githubusercontent.com/1115503/116770603-cbaee900-aa77-11eb-85ba-b7bc027dfa83.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: 3.6.13

**Additional context**
How to specify FMP key? It's not mentioned in README.

**Comment by alokan** [comment]
Set the GT_API_KEY_FINANCIALMODELINGPREP environment variable, or change API_KEY_FINANCIALMODELINGPREP in config_terminal.

**Comment by arisliang** [comment]
Got it, thanks.
