### ISSUE TITLE
[Bug] Unable to run op> chains: Error in request.get

### ISSUE THREAD

**Issue by arisliang** [DidierRLopes/GamestonkTerminal#424]
**Describe the bug**
Unable to run op> chains. It gives this error:
>Error in request.get -- check token
'NoneType' object is not subscriptable

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior
1. load ticker, e.g. MSFT
2. op> exp
3. error

**Screenshots**
![image](https://user-images.githubusercontent.com/1115503/116770998-817b3700-aa7a-11eb-85b3-3b4673320621.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: 3.6.13

**Comment by alokan** [comment]
GT_TRADIER_TOKEN

https://developer.tradier.com/getting_started

**Comment by alokan** [comment]
Look through the README and set up all of your keys. Most of these things you're reporting are errors stemming from you not having the api keys set up, and not actually bugs.

**Comment by arisliang** [comment]
I couldn't find other tags more suitable. Perhaps improvements?

The README key doesn't indicate which command needs what key, and the error message from the terminal doesn't say which key it's looking for either.

>Look through the README and set up all of your keys

I'm in the process of doing that, but step by step.

**Comment by alokan** [comment]
Oh, You can use open a blank issue after the list of tags if you want. I didn't know it was making you choose one. 

> The README key doesn't indicate which command needs what key, and the error message from the terminal doesn't say which key it's looking for either.

True, but if you're testing everything eventually you'll need them all.

**Comment by arisliang** [comment]
Oh I didn't notice there's a blank issue option, it's so much muted comparing with the big green button for the existing tags.

So far I tested all, but doesn't seem to need Alpha Vantage, Twitter, Polygon
