### ISSUE TITLE
[Bug] Error run op> info: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by arisliang** [DidierRLopes/GamestonkTerminal#425]
**Describe the bug**
Error run op> info:
>object of type 'NoneType' has no len()

**To Reproduce**
1. load ticker, e.g. MSFT
2. op> info
3. close the browser, which opens up successfully
4. error info appears in terminal

**Screenshots**
![image](https://user-images.githubusercontent.com/1115503/116771458-24818000-aa7e-11eb-89ca-33d503cff70b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: 3.6.13

**Additional context**
Browser opens up successfully, may indicate this is just some minor error.

**Comment by alokan** [comment]
What ticker are you using? is it MSFT? I'm assuming you set up selenium since the browser is opening. Does the browser take you to barchart and show the information when it opens?

**Comment by arisliang** [comment]
Yes, I'm using MSFT.

the browser does take it to barchart and show the website.

![image](https://user-images.githubusercontent.com/1115503/116772621-eaff4380-aa82-11eb-9eb3-a1b476a16618.png)

**Comment by arisliang** [comment]
Oh If I let the browser run long enough until the loading indicator settles, the error is gone.

Looks like it's just the browser is taking time to load. All good now.
