### ISSUE TITLE
Key already registered with the same priority: GroupSpatialSoftmax

### ISSUE THREAD

**Issue by Pranav4399** [DidierRLopes/GamestonkTerminal#47]
When i try to run python gamestonk_terminal.py in conda environment, it says "Key already registered with the same priority: GroupSpatialSoftmax". Any solutions ?

**Comment by DidierRLopes** [comment]
Hey @Pranav4399 ,

I've not come across this before. I'm improving requirements.txt file, this may help you!

**Comment by BigCandyBunny** [comment]
Hi,
I experienced the same error on Windows 10. This error comes from PyTorch. If you installed using pip, please use 'pip uninstall pytorch'. I don't know anything about your SW configuration on your HW rig. Thus, assuming Windows 10 and Anacond/Miniconda you may check out [https://pytorch.org/get-started/locally/#anaconda] and install it directly in your local environment.

**Comment by DidierRLopes** [comment]
Closing this issue, as I'm assuming that @BigCandyBunny solution worked
