### ISSUE TITLE
Installing fbprophet and appscript on Windows

### ISSUE THREAD

**Issue by luger1** [DidierRLopes/GamestonkTerminal#48]
Installing the requirements fbprophet and appscript fails on Windows 10 with Python 3.8.8 64bit Version. Is there a fix? I read that fbprophet needs a compiler on windows, but I couldn't figure it out yet. If there is an easy fix, I appreciate it!

**Comment by DidierRLopes** [comment]
Hey @luger1 ,

The appscript shouldn't be necessary, and the fbprophet is a pain.

But I'm working on fixing the requirements.txt and overall requirements and package dependencies this weekend!

**Comment by luger1** [comment]
I got it working by simply editing the requirements.txt this way:

```
appscript -> delete
fbprophet -> delete
cython -> delete version number
gensim -> delete version number
scipy -> change version to scipy==1.5.2
```

then install normally with pip:
`pip install -r requirements.txt
`

then install fbprophet with conda:
`conda install -c conda-forge fbprophet -y`

Conda fixes the compiler problem that you run into on windows.
