### ISSUE TITLE
Proper typing

### ISSUE THREAD

**Issue by exislow** [DidierRLopes/GamestonkTerminal#51]
Python 3 offers typing support: https://docs.python.org/3/library/typing.html

You are still using prefixes in your method parameters like `s_`, `l_` etc. to indicate, that a parameter must be a string or list etc.

Why do not use Python3 typing instead? `l_whatever` will become `whatever: list`

**Comment by DidierRLopes** [comment]
Hey,

I guess that in here I picked up my coding C/C++ standards habit, where by convention you specify the type of variable. 

I think in python this is not so common, but I also think it doesn't hurt. And if the function you're working on is rather long, or there's a long line of code, it's useful to know the type of the variable you are accessing.

**Comment by exislow** [comment]
Yes I agree, that typing is good. But why do not you use the typing system Python offers you? https://docs.python.org/3/library/typing.html

Maybe this was not really clear in my first comment.

**Comment by aia** [comment]
Started getting addressed - https://github.com/DidierRLopes/GamestonkTerminal/pull/101
