### ISSUE TITLE
Feature request: built in screener using trading views api or similiar 

### ISSUE THREAD

**Issue by saintsupremacy** [DidierRLopes/GamestonkTerminal#66]
While we can already see the sentiment of the market. In my opinion it would be nice to see and screen out different stock. For instance on trading view I love to filter my stocks between $.10-10$ by descending volume. I just think if it had a screener feature then this terminal would really be above everything else.

**Comment by DidierRLopes** [comment]
Hey @saintsupremacy,

You're right. This is a great idea, and I should have come up with it from the start. Thanks for this.

We'll work on this in the near future!

**Comment by noahkuhn** [comment]
Agreed, I was just thinking about this type of API-driven screener for my personal trading bot, so if it can incorporated into this project, I bet it would be super helpful in your next project doing the trading bot...

**Comment by DidierRLopes** [comment]
@saintsupremacy @noahkuhn took a bit longer than intended but finally managed to get around this. See #314 

Let me know if you feel like that menu should have something else!

I'll close this issue for now

**Comment by noahkuhn** [comment]
Just outstanding, thank you, I am super impressed.

**Comment by DidierRLopes** [comment]
> Just outstanding, thank you, I am super impressed.

Amazing, happy you like it!

Feel free to add a nice preset in here https://github.com/DidierRLopes/GamestonkTerminal/tree/screener-menu/gamestonk_terminal/screener/presets :)
