### ISSUE TITLE
[Feature] Support for asynchronous requests and data exports

### ISSUE THREAD

**Issue by EvilTeliportist** [DidierRLopes/GamestonkTerminal#7]
In true algotrading fashion having support for data exports would be really helpful (csv probably) for those trying to perform other analysis on the data without directly building onto the terminal itself. Maybe an abstract `Data` class with methods for flexible loading/exporting would be best for this, but you're the expert. Also, support for multiple ticker data requests would be useful when trying to compile and export this data, so some implementation of `asyncio` could be beneficial there in the long term for those trying to gather large quantities of data on slower connections.

Also, I love these small Easter egg type things: `print("Hope you made money today. Good bye my lover, good bye my friend.\n")`

**Comment by DidierRLopes** [comment]
Thank you for feedback.

That is indeed a good idea! If you want to work on it, feel free to create a PR for it.  Otherwise I'll get this done at some point in the future  :)

**Comment by DidierRLopes** [comment]
This has now been done by #119 !

Will close this issue on that basis :)
