### ISSUE TITLE
How to you load a stock? 

### ISSUE THREAD

**Issue by CarloCobal** [DidierRLopes/GamestonkTerminal#71]
Hi there!
The -t S_ticker [-s S_start_date]... is confusing me. What does the -t mean, do I put the date there? What is going on haha

Thank you,
Quaid

**Comment by DidierRLopes** [comment]
Hey @CarloCobal ,

This is following the linux convention where you usually do:
`command_name -flag value`

The best way for you to learn what is going on is to do:
`command_name -h` which shows the help menu.

In your case:
`load -t  TSLA -s 2020-06-04`
it means you are performing the command load, the ticker (`-t`) you want is `TSLA`, and the starting date (`-s`) is `2020-06-04`. 

Let me know if that sounds good!

**Comment by CarloCobal** [comment]
Yeah that makes sense thank you! 

I like your idea of loading the stock then using the analysis on the loaded ticker. In your example you have TSLA loaded, could you provide an example passing the loaded item to a sentiment or "disc" read? 

Sincerely,
Quaid

**Comment by shadycuz** [comment]
@CarloCobal 

Once loaded all the other commands will use it. So load the stock and then run something like `pred` -> `mlp`

**Comment by universvm** [comment]
Perhaps we could add some sample commands to the README?

**Comment by shadycuz** [comment]
@universvm I think we have at least two PR's working on updated docks. Will let you know when merged.

**Comment by DidierRLopes** [comment]
Hey guys,

Have a look at https://github.com/DidierRLopes/GamestonkTerminal#getting-started .

I'll close this issue, re-open it if you have any suggestion to improve this.
