### ISSUE TITLE
prediction days

### ISSUE THREAD

**Issue by regularperson2586** [DidierRLopes/GamestonkTerminal#72]
Hey, excellent work man. Is there a way to set prediction days ? i.e to just 1? cant find anything relating to it

**Comment by shadycuz** [comment]
@regularperson2586 Most of the commands have a "help" section. So for prediction using mlp you can type `mlp -h` and that will show you all the options. 

Think your looking for `mlp -d 1`.

I'm going to close this issue but please open it back up if that wasn't what you were looking for =)


- GamestonkTerminal 🚀 🌔
