### ISSUE TITLE
Demo for non tech people

### ISSUE THREAD

**Issue by jeetpatel910998** [DidierRLopes/GamestonkTerminal#79]
This looks pretty nice but I do not have any technical background on how to use this, can someone explain or demo please? Thanks in advance, I have a MacBook.

**Comment by shadycuz** [comment]
@jeetpatel910998 we are working on making this easier to get installed for users with any technical ability. We will reply back when we have docker and pip installation and abilities and supporting documentation.

**Comment by DidierRLopes** [comment]
Hey, have a look at https://github.com/DidierRLopes/GamestonkTerminal#getting-started. I added an usage example

I'll close this issue, re-open it if it's not good enough or you have any suggestion.
