### ISSUE TITLE
[FR] Interest rate data

### ISSUE THREAD

**Issue by nanman357** [DidierRLopes/GamestonkTerminal#87]
**What's the problem of not having this feature?**
Would it be possible to have interest rate data available through the terminal? 
Example: USD interest rate curve, official quotes from ON tenor to 1Y (example sourse: https://stooq.com/q/d/?s=ukousd1y )
Further tenors from 2Y can be from swap quotes like here : https://www.chathamfinancial.com/technology/us-market-rates

**Describe the solution you would like**
Have a history of IR tenors available. Without this, discounting is impossible.

**Describe alternatives you've considered**
ALternatively, finding a list of discount factors for future dates (ex. if today = 2020-12-31, find df's starting from 2021-01-04 to say 2051-01-02).

**Additional information**
Besides USD, it would be beneficial to have this solution for other currencies such as GBP, EUR, JPY and other nieche currencies as CND, AUD, NZD, PLN, SGD etc. (just an example list of currencies).

This would require introduce a different calendat for each location (because ex. there's no Marthin Luther King day in Eurozone).

**Comment by DidierRLopes** [comment]
I believe #199 addresses this. Is this correct @jmaslek ?

**Comment by jmaslek** [comment]
I think so.  Most of those should be on the fred site - which can be accessed with the custom function.

Did not do the discount factors.

**Comment by DidierRLopes** [comment]
I'll close this as it has been addressed from #199 . Feel free to re-open it if you disagree
