### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow==2.4.1  [Bug]

### ISSUE THREAD

**Issue by cphoover** [DidierRLopes/GamestonkTerminal#93]
**Describe the bug**
As described in title my install is erroring with:
```
Could not find a version that satisfies the requirement tensorflow==2.4.1 
```

**To Reproduce**
pip3 -r install requirements.txt

**Comment by shadycuz** [comment]
@cphoover What is the `pip` version? Tensorflow only support `pip` >= `2.19`.

**Comment by LordFahrenheit** [comment]
This is a Windows-based error. Had the same error, but works fine in Ubuntu VM. pip was freshly installed as was python3.

**Comment by drzhouq** [comment]
make sure your python is greater or equal to 3.6.8 but no more than 3.7. run `python --version` to figure out.

**Comment by DidierRLopes** [comment]
I'll close this Issue. If the issue persists feel free to open a new one!
