### ISSUE TITLE
[FR] Correlation with given tickers over specified amount of time

### ISSUE THREAD

**Issue by universvm** [DidierRLopes/GamestonkTerminal#97]
**What's the problem of not having this feature?**
It'd be cool to be able to correlate stocks for a specific amount of time. This is interesting specifically for stocks like AMC, GME and BB that have been surprisingly correlated, and others that have been almost uncorrelated between each others. 

**Describe the solution you would like**
I think as a solution, perhaps as part as the due diligence an input of a list of tickers say `['GME', 'BB', 'AAPL']` and a specified amount of time say `start=START_DATE, end=END_DATE or None`. If None the algorithm could calculate until the current date. Or perhaps it could be a specified number of days.

Ideally there should be a correlation matrix output (n, n) where n is the number of tickers chosen.

**Describe alternatives you've considered**
I could do this on excel or just manually on some website, but there's not much flexibility. Especially now that some stocks look very uncorrelated compared to GME, it's useful to see their performance.

**Additional information**
If you need help with the implementation I could help contribute maybe around May, I'm relatively familiar with numpy. I think the function could literally just call pandas https://datatofish.com/correlation-matrix-pandas/ or https://towardsdatascience.com/better-heatmaps-and-correlation-matrix-plots-in-python-41445d0f2bec

**Comment by aia** [comment]
Definitely! Correlation matrices are also used in portfolio analysis. 

https://github.com/robertmartin8/PyPortfolioOpt/blob/master/cookbook/2-Mean-Variance-Optimisation.ipynb

**Comment by universvm** [comment]
@aia perhaps I misread the pr but I don't think this was addressed? Let me know if you need a hand

**Comment by DidierRLopes** [comment]
I think the wrong PR was linked, see #141. 

A new menu was created for this, called comparison_analysis.
https://github.com/DidierRLopes/GamestonkTerminal/tree/main/gamestonk_terminal/comparison_analysis#corr

On the ROADMAP we have to add a comparison based on fundamentals, should be coming soon :)
